import { hunterMeats, hunterPelts } from "../JOBS/HUNTER.js";

const ItemCategory = {
  WEAPON: "weapon",
  AMMO: "ammo",
  FOOD: "food",
  DRINK: "drink",
  MEDICAL: "medical",
  TOOLS: "tools",
  MATERIALS: "materials",
  PARTS: "parts",
  DRUGS: "drug",
  KITS: "kits",
  VEST: "Vest",
};

const ItemAccessKey = {
  // No special access - general purpose items
  NONE: "none",

  // Weapons by slot
  PRIMARY_WEAPON: "PRIMARY_WEAPON",
  SECONDARY_WEAPON: "SECONDARY_WEAPON",
  MELEE: "MELEE",

  // Ammunition types
  PISTOL_AMMO: "PISTOL_AMMO",
  RIFLE_AMMO: "RIFLE_AMMO",
  SHOTGUN_AMMO: "SHOTGUN_AMMO",
  SNIPER_AMMO: "SNIPER_AMMO",
  // The musket's engine ammo type is AMMO_SHOTGUN, but it gets its OWN
  // inventory key: sharing SHOTGUN_AMMO would let a $12 musket ball load the
  // $32,000 Pump Shotgun. Mirrored in the gamemode's ItemAccessKey enum
  // (server/high-roleplay/inventory/itemProperties.ts) and in AmmoAccessKey
  // (shared/weapon.shared.ts) — all three need the member.
  MUSKET_AMMO: "MUSKET_AMMO",

  // Tools and equipment
  TOOL: "TOOL",
  KIT: "KIT",

  // For future use (not currently in your codebase)
  // BACKPACK = 'BACKPACK',
  // ARMOR = 'ARMOR',
  // HELMET = 'HELMET',
  // MASK = 'MASK',
  // CLOTHES = 'CLOTHES',
  // ACCESSORY = 'ACCESSORY',
  // BINOCULARS = 'BINOCULARS',
  // HANDCUFFS = 'HANDCUFFS',
  // RADIO = 'RADIO'
};

const rawFood = {
  item_drink_vodka: {
    name: "item_drink_vodka",
    label: "Vodka",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.DRINK,
    canUSE: true,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
    item_drink_tequila: {
    name: "item_drink_tequila",
    label: "Tequila",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.DRINK,
    canUSE: true,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
    item_drink_beer: {
    name: "item_drink_beer",
    label: "Beer",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.DRINK,
    canUSE: true,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },



  item_cooked_food_fires: {
    name: "item_cooked_food_fires",
    label: "Cooked Fries",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_cooked_food_burger_meat: {
    name: "item_cooked_food_burger_meat",
    label: "Cooked burger meat",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_cooked_food_burger_meat_vegan: {
    name: "item_cooked_food_burger_meat_vegan",
    label: "Cooked burger meat vegan",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },

  item_cooked_food_chicken: {
    name: "item_cooked_food_chicken",
    label: "Cooked Chicken",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },

  item_food_burger_bun: {
    name: "item_food_burger_bun",
    label: "Burger Bun",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },

  item_food_ketchup: {
    name: "item_food_ketchup",
    label: "Ketchup",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },

  item_food_sliced_cheese: {
    name: "item_food_sliced_cheese",
    label: "Sliced Cheese",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_burger_meat: {
    name: "item_raw_food_burger_meat",
    label: "Raw Burger Meat",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_burger_meat_vegan: {
    name: "item_raw_food_burger_meat_vegan",
    label: "Raw Burger Meat Vegan",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_chicken: {
    name: "item_raw_food_chicken",
    label: "Raw Chicken",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_lettuce: {
    name: "item_raw_food_lettuce",
    label: "Raw Lettuce",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_onion: {
    name: "item_raw_food_onion",
    label: "Raw Onion",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_pickle: {
    name: "item_raw_food_pickle",
    label: "Raw Pickle",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_potato: {
    name: "item_raw_food_potato",
    label: "Raw Potato",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_sliced_lettuce: {
    name: "item_raw_food_sliced_lettuce",
    label: "Raw Sliced Lettuce",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_sliced_onion: {
    name: "item_raw_food_sliced_onion",
    label: "Raw Sliced Onion",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_sliced_pickle: {
    name: "item_raw_food_sliced_pickle",
    label: "Raw Sliced Pickle",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_sliced_potato: {
    name: "item_raw_food_sliced_potato",
    label: "Raw Sliced Potato",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_sliced_tomato: {
    name: "item_raw_food_sliced_tomato",
    label: "Raw Sliced Tomato",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_tomato: {
    name: "item_raw_food_tomato",
    label: "Raw Tomato",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_food_burger: {
    name: "item_food_burger",
    label: "Food burger",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: true,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_food_cheese_burger: {
    name: "item_food_cheese_burger",
    label: "Food Cheese burger",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: true,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_food_chicken_burger: {
    name: "item_food_chicken_burger",
    label: "Food Chicken burger",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: true,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_food_double_burger: {
    name: "item_food_double_burger",
    label: "Food Double burger",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: true,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_food_double_cheese_burger: {
    name: "item_food_double_cheese_burger",
    label: "Food Double Cheese burger",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: true,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_food_fries: {
    name: "item_food_fries",
    label: "Food Fries",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: true,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_food_vegan_burger: {
    name: "item_food_vegan_burger",
    label: "Food Vegan Burger",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: true,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
};

export const MiningItems = {
  kit_antiSharp: {
    name: "kit_antiSharp",
    label: "anti sharp kit",
    accessKey: ItemAccessKey.KIT,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.KITS,
    canUnStack: false,
    weight: 2,
    durability: 100,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  kit_radioactive: {
    name: "kit_radioactive",
    label: "anti radiation kit ",
    accessKey: ItemAccessKey.KIT,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.KITS,
    canUnStack: false,
    durability: 100,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  kit_gas: {
    name: "kit_gas",
    label: "anti gas kit",
    accessKey: ItemAccessKey.KIT,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.KITS,
    canUnStack: false,
    durability: 100,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_binoculars: {
    name: "item_binoculars",
    label: "Binoculars",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_fireworks: {
    name: "item_fireworks",
    label: "Fireworks",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 5,
    canTrade: true,
  },

  item_fireworks_box: {
    name: "item_fireworks_box",
    label: "Fireworks Box",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 5,
    canTrade: true,
  },
  item_broken_lock_pick: {
    name: "item_broken_lock_pick",
    label: "Broken Lock Pick",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 10,
    canTrade: true,
  },
  item_pickaxe_lvl_1: {
    name: "item_pickaxe_lvl_1",
    label: "pickaxe lvl 1",
    accessKey: ItemAccessKey.TOOL,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    durability: 100,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_pickaxe_lvl_2: {
    name: "item_pickaxe_lvl_2",
    label: "pickaxe lvl 2",
    accessKey: ItemAccessKey.TOOL,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    durability: 100,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_pickaxe_lvl_3: {
    name: "item_pickaxe_lvl_3",
    label: "pickaxe lvl 3",
    accessKey: ItemAccessKey.TOOL,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    weight: 2,
    canStack: false,
    durability: 100,
    maxStack: 1,
    canTrade: true,
  },
  item_pickaxe_lvl_4: {
    name: "item_pickaxe_lvl_4",
    label: "pickaxe lvl 4",
    accessKey: ItemAccessKey.TOOL,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    durability: 100,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_bar_auriron: {
    name: "item_bar_auriron",
    label: "aur iron bar",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_bar_gildiron: {
    name: "item_bar_gildiron",
    label: "gild iron bar",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_bar_gold: {
    name: "item_bar_gold",
    label: "gold bar",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_bar_iron: {
    name: "item_bar_iron",
    label: "iron bar",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_gem_Amberite: {
    name: "item_gem_Amberite",
    label: "amberite gem",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: false,
    weight: 0.3,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_gem_aqualith: {
    name: "item_gem_aqualith",
    label: "aqualith gem",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: false,
    weight: 0.3,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_gem_luminite: {
    name: "item_gem_luminite",
    label: "luminite gem",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: false,
    weight: 0.3,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_ore_coal: {
    name: "item_ore_coal",
    label: "coal ore",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },
  item_ore_gold: {
    name: "item_ore_gold",
    label: "gold ore",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },
  item_ore_iron: {
    name: "item_ore_iron",
    label: "iron ore",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },

  item_ore_stone: {
    name: "item_ore_stone",
    label: "stone",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },

  item_ore_sulfur: {
    name: "item_ore_sulfur",
    label: "sulfur",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },
  item_mining_map: {
    name: "item_mining_map",
    label: "MINING MAP",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    category: ItemCategory.TOOLS,
  },
};

export const medicalItems = {
  item_pain_killer_pill: {
    name: "item_pain_killer_pill",
    label: "pain killer pill",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.MEDICAL,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },
  item_fabric: {
    name: "item_fabric",
    label: "fabric",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },

  item_ethanol: {
    name: "item_ethanol",
    label: "ethanol",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },

  item_empty_pill_capsule: {
    name: "item_empty_pill_capsule",
    label: "empty pill capsule",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },

  item_medicine_stablizer: {
    name: "item_medicine_stablizer",
    label: "medicine stablizer",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },

  item_capsaicin_powder: {
    name: "item_capsaicin_powder",
    label: "capsaicin powder",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },

  item_pain_killer_powder: {
    name: "item_pain_killer_powder",
    label: "pain killer powder",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },
};
const Vests = {
  item_vest_1: {
    name: "item_vest_1",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_2: {
    name: "item_vest_2",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_3: {
    name: "item_vest_3",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_4: {
    name: "item_vest_4",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_5: {
    name: "item_vest_5",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_6: {
    name: "item_vest_6",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_7: {
    name: "item_vest_7",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_8: {
    name: "item_vest_8",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_9: {
    name: "item_vest_9",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_10: {
    name: "item_vest_10",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_11: {
    name: "item_vest_11",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_12: {
    name: "item_vest_12",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_13: {
    name: "item_vest_13",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_14: {
    name: "item_vest_14",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_15: {
    name: "item_vest_15",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_16: {
    name: "item_vest_16",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_17: {
    name: "item_vest_17",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
};
export const weaponsItem = {
  item_weapon_knife: {
    name: "item_weapon_knife",
    label: "knife",
    accessKey: ItemAccessKey.MELEE,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_melee_machete: {
    name: "item_melee_machete",
    label: "machete",
    accessKey: ItemAccessKey.MELEE,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_revolver: {
    name: "item_weapon_revolver",
    label: "Heavy Revolver",
    accessKey: ItemAccessKey.SECONDARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_double_action_revolver: {
    name: "item_weapon_double_action_revolver",
    label: "Double Revolver",
    accessKey: ItemAccessKey.SECONDARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_weapon_db_shotgun: {
    name: "item_weapon_db_shotgun",
    label: "Double Barrel Shotgun",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_micro_smg: {
    name: "item_weapon_micro_smg",
    label: "Micro SMG",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_sawnoff_shotgun: {
    name: "item_weapon_sawnoff_shotgun",
    label: "Sawed-Off Shotgun",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_compact_rifle: {
    name: "item_weapon_compact_rifle",
    label: "Compact Rifle",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_bullet_7_62_mm: {
    name: "item_bullet_7_62_mm",
    label: "7.62mm bullet",
    accessKey: ItemAccessKey.SNIPER_AMMO,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    category: ItemCategory.AMMO,
    weight: 0.02,
    canStack: true,
    maxStack: 250,
    canTrade: true,
  },
  item_bullet_5_56_mm: {
    name: "item_bullet_5_56_mm",
    label: "5.56mm bullet",
    accessKey: ItemAccessKey.RIFLE_AMMO,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.AMMO,
    canUnStack: true,
    weight: 0.02,
    canStack: true,
    maxStack: 250,
    canTrade: true,
  },

  item_bullet_shotgun: {
    name: "item_bullet_shotgun",
    label: "shotgun shell",
    accessKey: ItemAccessKey.SHOTGUN_AMMO,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.AMMO,
    canDrop: false,
    canUnStack: true,
    weight: 0.05,
    canStack: true,
    maxStack: 250,
    canTrade: true,
  },
  item_weapon_advanced_rifle: {
    name: "item_weapon_advanced_rifle",
    label: "Advanced Rifle",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.WEAPON,
    canDrop: false,
    canUnStack: false,
    weight: 0.01,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_combat_mg: {
    name: "item_weapon_combat_mg",
    label: "Mg Rifle",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.WEAPON,
    canDrop: false,
    canUnStack: false,
    weight: 0.01,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_sniper_rifle: {
    name: "item_weapon_sniper_rifle",
    label: "Sniper Rifle",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.WEAPON,
    canDrop: false,
    canUnStack: false,
    weight: 0.07,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_carbine_rifle: {
    name: "item_weapon_carbine_rifle",
    label: "Carbine Rifle",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.WEAPON,
    canDrop: false,
    canUnStack: false,
    weight: 0.07,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_assault_shotgun: {
    name: "item_weapon_assault_shotgun",
    label: "assault shotgun",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.WEAPON,
    canDrop: false,
    canUnStack: false,
    weight: 3.5,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_smg: {
    name: "item_weapon_smg",
    label: "smg",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_combat_pwd: {
    name: "item_weapon_combat_pwd",
    label: "combat pwd",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_weapon_combat_shotgun: {
    name: "item_weapon_combat_shotgun",
    label: "combat shotgun",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.WEAPON,
    canUnStack: false,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_weapon_heavy_rifle: {
    name: "item_weapon_heavy_rifle",
    label: "heavy rifle",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.WEAPON,
    canDrop: false,
    canUnStack: false,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_pump_shotgun: {
    name: "item_weapon_pump_shotgun",
    label: "Pump Shotgun",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.WEAPON,
    canUnStack: false,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_heavy_shotgun: {
    name: "item_weapon_heavy_shotgun",
    label: "heavy shotgun",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.WEAPON,
    canUnStack: false,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_weapon_stun_gun: {
    name: "item_weapon_stun_gun",
    label: "stun gun",
    accessKey: ItemAccessKey.SECONDARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_vest_police: {
    name: "item_vest_police",
    label: "Police Vest",
    accessKey: ItemAccessKey.NONE,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.VEST,
    canUSE: true,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_combat_pistol: {
    name: "item_weapon_combat_pistol",
    label: "combat pistol",
    accessKey: ItemAccessKey.SECONDARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_weapon_appistol: {
    name: "item_weapon_appistol",
    label: "AP Pistol",
    accessKey: ItemAccessKey.SECONDARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    durability: 100,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_bullet_9_mm: {
    name: "item_bullet_9_mm",
    label: "9mm bullet",
    accessKey: ItemAccessKey.PISTOL_AMMO,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.AMMO,
    canDrop: false,
    canUnStack: true,
    weight: 0.01,
    canStack: true,
    maxStack: 200,
    canTrade: true,
  },
  item_weapon_nightstick: {
    name: "item_weapon_nightstick",
    label: "night stick",
    accessKey: ItemAccessKey.MELEE,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.WEAPON,
    canDrop: false,
    canUnStack: false,
    weight: 0.5,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_weapon_flashlight: {
    name: "item_weapon_flashlight",
    label: "flashlight",
    accessKey: ItemAccessKey.SECONDARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.WEAPON,
    canDrop: false,
    canUnStack: false,
    weight: 0.5,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_melee_knife: {
    name: "item_melee_knife",
    label: "Knife",
    accessKey: ItemAccessKey.MELEE,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.WEAPON,
    canDrop: false,
    canUnStack: false,
    weight: 0.5,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
};

// ── Hunter: 32 pelts + 8 meats ────────────────────────────────────────────
// Derived from the same two tables that price them (JOBS/HUNTER.js) rather
// than typed out 40 times, so a species or a quality tier can never exist on
// the price sheet without an item definition to match. Names and labels come
// straight from those arrays; only the physical properties live here.
const hunterPeltItems = Object.fromEntries(
  hunterPelts.map((p) => [
    p.itemName,
    {
      name: p.itemName,
      label: p.label,
      accessKey: ItemAccessKey.NONE,
      canUSE: false,
      canDrop: true,
      category: ItemCategory.MATERIALS,
      canUnStack: true,
      weight: 1.2,
      canStack: true,
      maxStack: 20,
      canTrade: true,
    },
  ]),
);

const hunterMeatItems = Object.fromEntries(
  hunterMeats.map((m) => [
    m.itemName,
    {
      name: m.itemName,
      label: m.label,
      accessKey: ItemAccessKey.NONE,
      // cooking turns it into a FOOD item; raw meat is an input
      canUSE: false,
      canDrop: true,
      category: ItemCategory.MATERIALS,
      canUnStack: true,
      weight: 0.8,
      canStack: true,
      maxStack: 20,
      canTrade: true,
    },
  ]),
);

export const itemsProperties = {
  item_drink_water: {
    name: "item_drink_water",
    label: "mineral water",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.DRINK,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },

  item_drink_sprunk: {
    name: "item_drink_sprunk",
    label: "sprunk soda",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.DRINK,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_walkie_talkie: {
    name: "item_walkie_talkie",
    label: "walkie talkie",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_food_chocolate: {
    name: "item_food_chocolate",
    label: "chocolate bar",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.FOOD,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },

  item_food_hamburger: {
    name: "item_food_hamburger",
    label: "hamburger",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.FOOD,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  kit_antiSharp: {
    name: "kit_antiSharp",
    label: "anti sharp kit",
    accessKey: ItemAccessKey.KIT,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.KITS,
    canUnStack: false,
    weight: 2,
    durability: 100,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_repairkit: {
    name: "item_repairkit",
    label: "repair kit",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 10,
    canTrade: true,
  },

  item_hand_pilers: {
    name: "item_hand_pilers",
    label: "Tools Pliers",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 80,
    canTrade: true,
  },

  item_multi_metter: {
    name: "item_multi_metter",
    label: "Tools Multimeter",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_drink_fanta: {
    name: "item_drink_fanta",
    label: "fanta",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.DRINK,
    canUnStack: true,
    weight: 0.3,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },

  item_medical_bandage: {
    name: "item_medical_bandage",
    label: "bandage",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.MEDICAL,
    canUnStack: true,
    weight: 0.5,
    canStack: true,
    maxStack: 10,
    canTrade: true,
  },

  item_medical_first_aid: {
    name: "item_medical_first_aid",
    label: "first aid kit",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.MEDICAL,
    canUnStack: true,
    weight: 0.5,
    canStack: true,
    maxStack: 5,
    canTrade: true,
  },

  item_fuel_can: {
    name: "item_fuel_can",
    label: "fuel can",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.5,
    canStack: true,
    maxStack: 10,
    canTrade: true,
  },

  item_food_burger: {
    name: "item_food_burger",
    label: "burger",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.FOOD,
    canUnStack: true,
    weight: 0.5,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  ...MiningItems,
  ...medicalItems,
  ...weaponsItem,
  ...rawFood,
  ...Vests,
  // Weapon-part items (barrels/triggers/grips/scope/stock) were REMOVED July 2026
  // — gang weapons are crafted from item_military_component (weapon-shop robbery
  // loot) instead. Definition ported from the live server config.
  item_military_component: {
    name: "item_military_component",
    label: "Military Component",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    canDelete: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    canStack: true,
    maxStack: 500,
    weight: 0.1,
    canTrade: true,
    isIllegal: true,
  },

  item_reinforced_steel: {
    name: "item_reinforced_steel",
    label: "reinforced steel",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.PARTS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },
  item_coca_leaves: {
    name: "item_coca_leaves",
    label: "coca leaves",
    accessKey: ItemAccessKey.NONE,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.DRUGS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_cocain_pack: {
    name: "item_cocain_pack",
    label: "cocain pack",
    accessKey: ItemAccessKey.NONE,
    canDelete: false,
    isIllegal: true,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.DRUGS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },
  item_cocain_powder: {
    name: "item_cocain_powder",
    label: "cocain powder",
    accessKey: ItemAccessKey.NONE,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.DRUGS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },

  item_mdma_pill: {
    name: "item_mdma_pill",
    label: "mdma pill",
    accessKey: ItemAccessKey.NONE,
    canDelete: false,
    isIllegal: true,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.DRUGS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },
  item_mdma_powder: {
    name: "item_mdma_powder",
    label: "mdma powder",
    accessKey: ItemAccessKey.NONE,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.DRUGS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },
  item_mdp2p: {
    name: "item_mdp2p",
    label: "mdp2p",
    accessKey: ItemAccessKey.NONE,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.DRUGS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },
  item_saffarole_oil: {
    name: "item_saffarole_oil",
    label: "saffarole oil",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.DRUGS,
    isIllegal: true,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },
  item_weed: {
    name: "item_weed",
    label: "weed",
    accessKey: ItemAccessKey.NONE,
    canDelete: false,
    isIllegal: true,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.DRUGS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 40,
    canTrade: true,
  },

  item_saffarole_leave: {
    name: "item_saffarole_leave",
    label: "saffarole leave",
    accessKey: ItemAccessKey.NONE,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.DRUGS,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 40,
    canTrade: true,
  },
  item_acetone: {
    name: "item_acetone",
    label: "acetone",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },
  item_ammonia: {
    name: "item_ammonia",
    label: "ammonia",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },
  item_battery: {
    name: "item_battery",
    label: "battery",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.PARTS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_engine_oil: {
    name: "item_engine_oil",
    label: "Engine Oil",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: true,
    category: ItemCategory.PARTS,
    canUnStack: true,
    weight: 1.5,
    canStack: true,
    maxStack: 10,
    canTrade: true,
  },
  item_car_battery: {
    name: "item_car_battery",
    label: "Car Battery",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: true,
    category: ItemCategory.PARTS,
    canUnStack: true,
    weight: 4,
    canStack: true,
    maxStack: 5,
    canTrade: true,
  },
  item_empty_plastic_pack: {
    name: "item_empty_plastic_pack",
    label: "empty plastic pack",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.PARTS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },
  item_gun_powder: {
    name: "item_gun_powder",
    label: "gun powder",
    accessKey: ItemAccessKey.NONE,
    isIllegal: true,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },
  item_house_cleaner: {
    name: "item_house_cleaner",
    label: "house cleaner",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },
  item_methanol: {
    name: "item_methanol",
    label: "methanol",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 35,
    canTrade: true,
  },
  item_methylamine_crystal: {
    name: "item_methylamine_crystal",
    label: "methylamine crystal",
    accessKey: ItemAccessKey.NONE,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.DRUGS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },

  item_paint_color: {
    name: "item_paint_color",
    label: "paint color",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },

  item_lock_pick: {
    name: "item_lock_pick",
    label: "Lock Pick",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: true,
    isIllegal: true,
    weight: 1,
    canStack: true,
    maxStack: 10,
    canTrade: true,
  },

  // --- ATM robbery kit (features/atm-robbery) ---------------------------
  // The screwdriver opens the faceplate and is NEVER consumed; the chip does
  // the hack and is consumed the moment stage 2 completes.

  item_screwdriver: {
    name: "item_screwdriver",
    label: "Screwdriver",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 5,
    canTrade: true,
  },

  item_atm_hack_chip: {
    name: "item_atm_hack_chip",
    label: "Hacking Chip",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: true,
    isIllegal: true,
    weight: 1,
    canStack: true,
    maxStack: 10,
    canTrade: true,
  },

  item_sodium_bicarbonate: {
    name: "item_sodium_bicarbonate",
    label: "sodium bicarbonate",
    accessKey: ItemAccessKey.NONE,

    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 90,
    canTrade: true,
  },

  item_sulfuric_acid: {
    name: "item_sulfuric_acid",
    label: "sulfuric acid",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // JOB SPECS PACK (JOB_SPECS/) — Lumberjack, Mushroom Picker, Stonemason,
  // Hunter. Every entry here is mirrored by hand in the gamemode's own
  // catalog, server/high-roleplay/inventory/itemProperties.ts — that file is
  // the one grantStackableItem validates against, so an item missing there
  // throws on the very first harvest even though it is present here.
  // ═══════════════════════════════════════════════════════════════════════

  // ── Lumberjack (JOB_SPECS/05-Lumberjack.md) ──────────────────────────────
  item_log_pine: {
    name: "item_log_pine",
    label: "Pine Log",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 3,
    canStack: true,
    maxStack: 10, // [MANUAL] + [OBSERVED 102635] — 10 per cell
    canTrade: true,
  },
  item_log_oak: {
    name: "item_log_oak",
    label: "Oak Log",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 3,
    canStack: true,
    maxStack: 10,
    canTrade: true,
  },
  item_log_birch: {
    name: "item_log_birch",
    label: "Birch Log",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 3,
    canStack: true,
    maxStack: 10,
    canTrade: true,
  },
  item_log_maple: {
    name: "item_log_maple",
    label: "Maple Log",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 3,
    canStack: true,
    maxStack: 10,
    canTrade: true,
  },
  item_axe_common: {
    name: "item_axe_common",
    label: "Common Axe",
    accessKey: ItemAccessKey.TOOL,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    durability: 200, // [MANUAL] Description.txt — 200 trees
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  // ── Mushroom Picker (JOB_SPECS/06-MushroomPicker.md) ─────────────────────
  item_shovel: {
    name: "item_shovel",
    label: "Shovel",
    accessKey: ItemAccessKey.TOOL,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    durability: 200,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_mushroom_champignon: {
    name: "item_mushroom_champignon",
    label: "Champignon",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },
  item_mushroom_oyster: {
    name: "item_mushroom_oyster",
    label: "Oyster Mushroom",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },
  item_mushroom_honey: {
    name: "item_mushroom_honey",
    label: "Honey Fungus",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },
  item_mushroom_flyagaric: {
    name: "item_mushroom_flyagaric",
    label: "Fly Agaric",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },
  item_mushroom_chanterelle: {
    name: "item_mushroom_chanterelle",
    label: "Chanterelle",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },
  item_mushroom_russula: {
    name: "item_mushroom_russula",
    label: "Green Russula",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },
  item_mushroom_king: {
    name: "item_mushroom_king",
    label: "King Mushroom",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.2,
    canStack: true,
    maxStack: 25,
    canTrade: true,
  },

  // ── Stonemason (JOB_SPECS/07-Stonemason.md) ──────────────────────────────
  item_pickaxe_stone_1: {
    name: "item_pickaxe_stone_1",
    label: "Ordinary Pickaxe",
    accessKey: ItemAccessKey.TOOL,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    durability: 200,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_pickaxe_stone_2: {
    name: "item_pickaxe_stone_2",
    label: "Improved Pickaxe",
    accessKey: ItemAccessKey.TOOL,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    durability: 200,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_pickaxe_stone_3: {
    name: "item_pickaxe_stone_3",
    label: "Best Pickaxe",
    accessKey: ItemAccessKey.TOOL,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    durability: 200,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  // maxStack 500, NOT the 100 the refinery ores use: one 1500-unit sales window
  // has to fit in ~3 of a player's 30 slots or the bag-full branch fires
  // constantly, and a real player was observed holding 507 kg of iron.
  item_metal_iron: {
    name: "item_metal_iron",
    label: "Iron",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 500,
    canTrade: true,
  },
  item_metal_copper: {
    name: "item_metal_copper",
    label: "Copper",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 500,
    canTrade: true,
  },
  item_metal_silver: {
    name: "item_metal_silver",
    label: "Silver",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.02,
    canStack: true,
    maxStack: 500,
    canTrade: true,
  },
  item_metal_gold: {
    name: "item_metal_gold",
    label: "Gold",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.02,
    canStack: true,
    maxStack: 500,
    canTrade: true,
  },
  item_metal_diamond: {
    name: "item_metal_diamond",
    label: "Diamond",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.05,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },

  // ── Hunter (JOB_SPECS/08-Hunter.md) ──────────────────────────────────────
  // 32 pelts + 8 meats, built above from the JOBS/HUNTER.js tables.
  ...hunterPeltItems,
  ...hunterMeatItems,
  item_weapon_musket: {
    name: "item_weapon_musket",
    label: "Musket",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: false,
    category: ItemCategory.WEAPON,
    durability: 100,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_bullet_musket: {
    name: "item_bullet_musket",
    label: "Musket ball",
    accessKey: ItemAccessKey.MUSKET_AMMO,
    canDelete: false,
    isIllegal: false,
    canUSE: false,
    category: ItemCategory.AMMO,
    canDrop: false,
    canUnStack: true,
    weight: 0.05,
    canStack: true,
    maxStack: 500,
    canTrade: true,
  },
  // ...add more items here
};
