import { hunterMeats, hunterPelts } from "../JOBS/HUNTER.js";

const ItemCategory = {
  WEAPON: "weapon",
  AMMO: "ammo",
  FOOD: "food",
  DRINK: "drink",
  MEDICAL: "medical",
  TOOLS: "tools",
  MATERIALS: "materials",
  PARTS: "parts",
  DRUGS: "drug",
  KITS: "kits",
  VEST: "Vest",
};

const ItemAccessKey = {
  // No special access - general purpose items
  NONE: "none",

  // Weapons by slot
  PRIMARY_WEAPON: "PRIMARY_WEAPON",
  SECONDARY_WEAPON: "SECONDARY_WEAPON",
  MELEE: "MELEE",

  // Ammunition types
  PISTOL_AMMO: "PISTOL_AMMO",
  RIFLE_AMMO: "RIFLE_AMMO",
  SHOTGUN_AMMO: "SHOTGUN_AMMO",
  // The Hunter's musket uses SHOTGUN_AMMO — it has no dedicated key and no
  // dedicated ball item. Mirrored in the gamemode's ItemAccessKey enum
  // (server/high-roleplay/inventory/itemProperties.ts) and in AmmoAccessKey
  // (shared/weapon.shared.ts); none of the three carries MUSKET_AMMO.
  SNIPER_AMMO: "SNIPER_AMMO",

  // Tools and equipment
  TOOL: "TOOL",
  KIT: "KIT",
  // Vests. The gamemode enum has carried this since vests were added; this copy
  // did not, so every vest entry below would have emitted `accessKey: undefined`
  // and the inventory would not have known which slot they belong in.
  VEST: "VEST",

  // For future use (not currently in your codebase)
  // BACKPACK = 'BACKPACK',
  // ARMOR = 'ARMOR',
  // HELMET = 'HELMET',
  // MASK = 'MASK',
  // CLOTHES = 'CLOTHES',
  // ACCESSORY = 'ACCESSORY',
  // BINOCULARS = 'BINOCULARS',
  // HANDCUFFS = 'HANDCUFFS',
  // RADIO = 'RADIO'
};

const rawFood = {
  item_drink_vodka: {
    name: "item_drink_vodka",
    label: "Vodka",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.DRINK,
    canUSE: true,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
    item_drink_tequila: {
    name: "item_drink_tequila",
    label: "Tequila",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.DRINK,
    canUSE: true,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
    item_drink_beer: {
    name: "item_drink_beer",
    label: "Beer",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.DRINK,
    canUSE: true,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },



  item_cooked_food_fires: {
    name: "item_cooked_food_fires",
    label: "Cooked Fries",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_cooked_food_burger_meat: {
    name: "item_cooked_food_burger_meat",
    label: "Cooked burger meat",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_cooked_food_burger_meat_vegan: {
    name: "item_cooked_food_burger_meat_vegan",
    label: "Cooked burger meat vegan",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },

  item_cooked_food_chicken: {
    name: "item_cooked_food_chicken",
    label: "Cooked Chicken",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },

  item_food_burger_bun: {
    name: "item_food_burger_bun",
    label: "Burger Bun",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },

  item_food_ketchup: {
    name: "item_food_ketchup",
    label: "Ketchup",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },

  item_food_sliced_cheese: {
    name: "item_food_sliced_cheese",
    label: "Sliced Cheese",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_burger_meat: {
    name: "item_raw_food_burger_meat",
    label: "Raw Burger Meat",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_burger_meat_vegan: {
    name: "item_raw_food_burger_meat_vegan",
    label: "Raw Burger Meat Vegan",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_chicken: {
    name: "item_raw_food_chicken",
    label: "Raw Chicken",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_lettuce: {
    name: "item_raw_food_lettuce",
    label: "Raw Lettuce",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_onion: {
    name: "item_raw_food_onion",
    label: "Raw Onion",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_pickle: {
    name: "item_raw_food_pickle",
    label: "Raw Pickle",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_potato: {
    name: "item_raw_food_potato",
    label: "Raw Potato",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_sliced_lettuce: {
    name: "item_raw_food_sliced_lettuce",
    label: "Raw Sliced Lettuce",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_sliced_onion: {
    name: "item_raw_food_sliced_onion",
    label: "Raw Sliced Onion",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_sliced_pickle: {
    name: "item_raw_food_sliced_pickle",
    label: "Raw Sliced Pickle",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_sliced_potato: {
    name: "item_raw_food_sliced_potato",
    label: "Raw Sliced Potato",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_sliced_tomato: {
    name: "item_raw_food_sliced_tomato",
    label: "Raw Sliced Tomato",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_raw_food_tomato: {
    name: "item_raw_food_tomato",
    label: "Raw Tomato",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_food_burger: {
    name: "item_food_burger",
    label: "Food burger",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: true,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_food_cheese_burger: {
    name: "item_food_cheese_burger",
    label: "Food Cheese burger",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: true,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_food_chicken_burger: {
    name: "item_food_chicken_burger",
    label: "Food Chicken burger",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: true,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_food_double_burger: {
    name: "item_food_double_burger",
    label: "Food Double burger",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: true,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_food_double_cheese_burger: {
    name: "item_food_double_cheese_burger",
    label: "Food Double Cheese burger",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: true,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_food_fries: {
    name: "item_food_fries",
    label: "Food Fries",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: true,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_food_vegan_burger: {
    name: "item_food_vegan_burger",
    label: "Food Vegan Burger",
    accessKey: ItemAccessKey.NONE,
    canDelete: true,
    isIllegal: false,
    category: ItemCategory.FOOD,
    canUSE: true,
    canDrop: false,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
};

export const MiningItems = {
  kit_antiSharp: {
    name: "kit_antiSharp",
    label: "anti sharp kit",
    accessKey: ItemAccessKey.KIT,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.KITS,
    canUnStack: false,
    weight: 2,
    durability: 100,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  kit_radioactive: {
    name: "kit_radioactive",
    label: "anti radiation kit ",
    accessKey: ItemAccessKey.KIT,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.KITS,
    canUnStack: false,
    durability: 100,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  kit_gas: {
    name: "kit_gas",
    label: "anti gas kit",
    accessKey: ItemAccessKey.KIT,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.KITS,
    canUnStack: false,
    durability: 100,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_binoculars: {
    name: "item_binoculars",
    label: "Binoculars",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_fireworks: {
    name: "item_fireworks",
    label: "Fireworks",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 5,
    canTrade: true,
  },

  item_fireworks_box: {
    name: "item_fireworks_box",
    label: "Fireworks Box",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 5,
    canTrade: true,
  },
  item_broken_lock_pick: {
    name: "item_broken_lock_pick",
    label: "Broken Lock Pick",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 10,
    canTrade: true,
  },
  item_pickaxe_lvl_1: {
    name: "item_pickaxe_lvl_1",
    label: "pickaxe lvl 1",
    accessKey: ItemAccessKey.TOOL,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    durability: 100,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_pickaxe_lvl_2: {
    name: "item_pickaxe_lvl_2",
    label: "pickaxe lvl 2",
    accessKey: ItemAccessKey.TOOL,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    durability: 100,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_pickaxe_lvl_3: {
    name: "item_pickaxe_lvl_3",
    label: "pickaxe lvl 3",
    accessKey: ItemAccessKey.TOOL,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    weight: 2,
    canStack: false,
    durability: 100,
    maxStack: 1,
    canTrade: true,
  },
  item_pickaxe_lvl_4: {
    name: "item_pickaxe_lvl_4",
    label: "pickaxe lvl 4",
    accessKey: ItemAccessKey.TOOL,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    durability: 100,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_bar_auriron: {
    name: "item_bar_auriron",
    label: "aur iron bar",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_bar_gildiron: {
    name: "item_bar_gildiron",
    label: "gild iron bar",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_bar_gold: {
    name: "item_bar_gold",
    label: "gold bar",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_bar_iron: {
    name: "item_bar_iron",
    label: "iron bar",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_gem_Amberite: {
    name: "item_gem_Amberite",
    label: "amberite gem",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: false,
    weight: 0.3,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_gem_aqualith: {
    name: "item_gem_aqualith",
    label: "aqualith gem",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: false,
    weight: 0.3,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_gem_luminite: {
    name: "item_gem_luminite",
    label: "luminite gem",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: false,
    weight: 0.3,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_ore_coal: {
    name: "item_ore_coal",
    label: "coal ore",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },
  item_ore_gold: {
    name: "item_ore_gold",
    label: "gold ore",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },
  item_ore_iron: {
    name: "item_ore_iron",
    label: "iron ore",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },

  item_ore_stone: {
    name: "item_ore_stone",
    label: "stone",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },

  item_ore_sulfur: {
    name: "item_ore_sulfur",
    label: "sulfur",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },
  item_mining_map: {
    name: "item_mining_map",
    label: "MINING MAP",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    category: ItemCategory.TOOLS,
  },
};

export const medicalItems = {
  item_pain_killer_pill: {
    name: "item_pain_killer_pill",
    label: "pain killer pill",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.MEDICAL,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },
  item_fabric: {
    name: "item_fabric",
    label: "fabric",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },

  item_ethanol: {
    name: "item_ethanol",
    label: "ethanol",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },

  item_empty_pill_capsule: {
    name: "item_empty_pill_capsule",
    label: "empty pill capsule",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },

  item_medicine_stablizer: {
    name: "item_medicine_stablizer",
    label: "medicine stablizer",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },

  item_capsaicin_powder: {
    name: "item_capsaicin_powder",
    label: "capsaicin powder",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },

  item_pain_killer_powder: {
    name: "item_pain_killer_powder",
    label: "pain killer powder",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },
};
const Vests = {
  item_vest_1: {
    name: "item_vest_1",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_2: {
    name: "item_vest_2",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_3: {
    name: "item_vest_3",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_4: {
    name: "item_vest_4",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_5: {
    name: "item_vest_5",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_6: {
    name: "item_vest_6",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_7: {
    name: "item_vest_7",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_8: {
    name: "item_vest_8",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_9: {
    name: "item_vest_9",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_10: {
    name: "item_vest_10",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_11: {
    name: "item_vest_11",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_12: {
    name: "item_vest_12",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_13: {
    name: "item_vest_13",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_14: {
    name: "item_vest_14",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_15: {
    name: "item_vest_15",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_16: {
    name: "item_vest_16",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_17: {
    name: "item_vest_17",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
};
export const weaponsItem = {
  item_weapon_knife: {
    name: "item_weapon_knife",
    label: "knife",
    accessKey: ItemAccessKey.MELEE,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_melee_machete: {
    name: "item_melee_machete",
    label: "machete",
    accessKey: ItemAccessKey.MELEE,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_revolver: {
    name: "item_weapon_revolver",
    label: "Heavy Revolver",
    accessKey: ItemAccessKey.SECONDARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_double_action_revolver: {
    name: "item_weapon_double_action_revolver",
    label: "Double Revolver",
    accessKey: ItemAccessKey.SECONDARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_weapon_db_shotgun: {
    name: "item_weapon_db_shotgun",
    label: "Double Barrel Shotgun",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_micro_smg: {
    name: "item_weapon_micro_smg",
    label: "Micro SMG",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_sawnoff_shotgun: {
    name: "item_weapon_sawnoff_shotgun",
    label: "Sawed-Off Shotgun",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_compact_rifle: {
    name: "item_weapon_compact_rifle",
    label: "Compact Rifle",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_bullet_7_62_mm: {
    name: "item_bullet_7_62_mm",
    label: "7.62mm bullet",
    accessKey: ItemAccessKey.SNIPER_AMMO,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    canDrop: false,
    canUnStack: true,
    category: ItemCategory.AMMO,
    weight: 0.02,
    canStack: true,
    maxStack: 250,
    canTrade: true,
  },
  item_bullet_5_56_mm: {
    name: "item_bullet_5_56_mm",
    label: "5.56mm bullet",
    accessKey: ItemAccessKey.RIFLE_AMMO,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.AMMO,
    canUnStack: true,
    weight: 0.02,
    canStack: true,
    maxStack: 250,
    canTrade: true,
  },

  item_bullet_shotgun: {
    name: "item_bullet_shotgun",
    label: "shotgun shell",
    accessKey: ItemAccessKey.SHOTGUN_AMMO,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.AMMO,
    canDrop: false,
    canUnStack: true,
    weight: 0.05,
    canStack: true,
    maxStack: 250,
    canTrade: true,
  },
  item_weapon_advanced_rifle: {
    name: "item_weapon_advanced_rifle",
    label: "Advanced Rifle",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.WEAPON,
    canDrop: false,
    canUnStack: false,
    weight: 0.01,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_combat_mg: {
    name: "item_weapon_combat_mg",
    label: "Mg Rifle",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.WEAPON,
    canDrop: false,
    canUnStack: false,
    weight: 0.01,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_sniper_rifle: {
    name: "item_weapon_sniper_rifle",
    label: "Sniper Rifle",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.WEAPON,
    canDrop: false,
    canUnStack: false,
    weight: 0.07,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_carbine_rifle: {
    name: "item_weapon_carbine_rifle",
    label: "Carbine Rifle",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.WEAPON,
    canDrop: false,
    canUnStack: false,
    weight: 0.07,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_assault_shotgun: {
    name: "item_weapon_assault_shotgun",
    label: "assault shotgun",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.WEAPON,
    canDrop: false,
    canUnStack: false,
    weight: 3.5,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_smg: {
    name: "item_weapon_smg",
    label: "smg",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_combat_pwd: {
    name: "item_weapon_combat_pwd",
    label: "combat pwd",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_weapon_combat_shotgun: {
    name: "item_weapon_combat_shotgun",
    label: "combat shotgun",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.WEAPON,
    canUnStack: false,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_weapon_heavy_rifle: {
    name: "item_weapon_heavy_rifle",
    label: "heavy rifle",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.WEAPON,
    canDrop: false,
    canUnStack: false,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_pump_shotgun: {
    name: "item_weapon_pump_shotgun",
    label: "Pump Shotgun",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.WEAPON,
    canUnStack: false,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_heavy_shotgun: {
    name: "item_weapon_heavy_shotgun",
    label: "heavy shotgun",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.WEAPON,
    canUnStack: false,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_weapon_stun_gun: {
    name: "item_weapon_stun_gun",
    label: "stun gun",
    accessKey: ItemAccessKey.SECONDARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_vest_police: {
    name: "item_vest_police",
    label: "Police Vest",
    accessKey: ItemAccessKey.NONE,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.VEST,
    canUSE: true,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_weapon_combat_pistol: {
    name: "item_weapon_combat_pistol",
    label: "combat pistol",
    accessKey: ItemAccessKey.SECONDARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_weapon_appistol: {
    name: "item_weapon_appistol",
    label: "AP Pistol",
    accessKey: ItemAccessKey.SECONDARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    category: ItemCategory.WEAPON,
    durability: 100,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_bullet_9_mm: {
    name: "item_bullet_9_mm",
    label: "9mm bullet",
    accessKey: ItemAccessKey.PISTOL_AMMO,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.AMMO,
    canDrop: false,
    canUnStack: true,
    weight: 0.01,
    canStack: true,
    maxStack: 200,
    canTrade: true,
  },
  item_weapon_nightstick: {
    name: "item_weapon_nightstick",
    label: "night stick",
    accessKey: ItemAccessKey.MELEE,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.WEAPON,
    canDrop: false,
    canUnStack: false,
    weight: 0.5,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_weapon_flashlight: {
    name: "item_weapon_flashlight",
    label: "flashlight",
    accessKey: ItemAccessKey.SECONDARY_WEAPON,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.WEAPON,
    canDrop: false,
    canUnStack: false,
    weight: 0.5,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_melee_knife: {
    name: "item_melee_knife",
    label: "Knife",
    accessKey: ItemAccessKey.MELEE,
    canDelete: false,
    isIllegal: true,
    canUSE: false,
    category: ItemCategory.WEAPON,
    canDrop: false,
    canUnStack: false,
    weight: 0.5,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
};

// ── Hunter: 32 pelts + 8 meats ────────────────────────────────────────────
// Derived from the same two tables that price them (JOBS/HUNTER.js) rather
// than typed out 40 times, so a species or a quality tier can never exist on
// the price sheet without an item definition to match. Names and labels come
// straight from those arrays; only the physical properties live here.
const hunterPeltItems = Object.fromEntries(
  hunterPelts.map((p) => [
    p.itemName,
    {
      name: p.itemName,
      label: p.label,
      accessKey: ItemAccessKey.NONE,
      canUSE: false,
      canDrop: true,
      category: ItemCategory.MATERIALS,
      canUnStack: true,
      weight: 1.2,
      canStack: true,
      maxStack: 20,
      canTrade: true,
    },
  ]),
);

const hunterMeatItems = Object.fromEntries(
  hunterMeats.map((m) => [
    m.itemName,
    {
      name: m.itemName,
      label: m.label,
      accessKey: ItemAccessKey.NONE,
      // cooking turns it into a FOOD item; raw meat is an input
      canUSE: false,
      canDrop: true,
      category: ItemCategory.MATERIALS,
      canUnStack: true,
      weight: 0.8,
      canStack: true,
      maxStack: 20,
      canTrade: true,
    },
  ]),
);

export const itemsProperties = {
  item_drink_water: {
    name: "item_drink_water",
    label: "mineral water",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.DRINK,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },

  item_drink_sprunk: {
    name: "item_drink_sprunk",
    label: "sprunk soda",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.DRINK,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_walkie_talkie: {
    name: "item_walkie_talkie",
    label: "walkie talkie",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_food_chocolate: {
    name: "item_food_chocolate",
    label: "chocolate bar",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.FOOD,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },

  item_food_hamburger: {
    name: "item_food_hamburger",
    label: "hamburger",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.FOOD,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  kit_antiSharp: {
    name: "kit_antiSharp",
    label: "anti sharp kit",
    accessKey: ItemAccessKey.KIT,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.KITS,
    canUnStack: false,
    weight: 2,
    durability: 100,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_repairkit: {
    name: "item_repairkit",
    label: "repair kit",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 10,
    canTrade: true,
  },

  // §13.3 — the pliers are required for every electrician repair but had no
  // `durability`, so they were a one-time $2,000 purchase that lasted forever.
  // `maxStack: 80` on a durable tool is also wrong: a stack of 80 shares one
  // durability value. Mirrored in the gamemode's inventory/itemProperties.ts and
  // in JOBS/ELECTRIC.js `tools.pliersDurability` — all three must agree.
  item_hand_pilers: {
    name: "item_hand_pilers",
    label: "Tools Pliers",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false, // <- was true
    durability: 200, // <- NEW. 200 repairs ~= 3.8 h
    weight: 1,
    canStack: false, // <- was true
    maxStack: 1, // <- was 80
    canTrade: true,
  },

  item_multi_metter: {
    name: "item_multi_metter",
    label: "Tools Multimeter",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  item_drink_fanta: {
    name: "item_drink_fanta",
    label: "fanta",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.DRINK,
    canUnStack: true,
    weight: 0.3,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },

  item_medical_bandage: {
    name: "item_medical_bandage",
    label: "bandage",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.MEDICAL,
    canUnStack: true,
    weight: 0.5,
    canStack: true,
    maxStack: 10,
    canTrade: true,
  },

  item_medical_first_aid: {
    name: "item_medical_first_aid",
    label: "first aid kit",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.MEDICAL,
    canUnStack: true,
    weight: 0.5,
    canStack: true,
    maxStack: 5,
    canTrade: true,
  },

  item_fuel_can: {
    name: "item_fuel_can",
    label: "fuel can",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.5,
    canStack: true,
    maxStack: 10,
    canTrade: true,
  },

  item_food_burger: {
    name: "item_food_burger",
    label: "burger",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.FOOD,
    canUnStack: true,
    weight: 0.5,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  ...MiningItems,
  ...medicalItems,
  ...weaponsItem,
  ...rawFood,
  ...Vests,
  // Weapon-part items (barrels/triggers/grips/scope/stock) were REMOVED July 2026
  // — gang weapons are crafted from item_military_component (weapon-shop robbery
  // loot) instead. Definition ported from the live server config.
  item_military_component: {
    name: "item_military_component",
    label: "Military Component",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    canDelete: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    canStack: true,
    maxStack: 500,
    weight: 0.1,
    canTrade: true,
    isIllegal: true,
  },

  item_reinforced_steel: {
    name: "item_reinforced_steel",
    label: "reinforced steel",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.PARTS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },

  item_weed: {
    name: "item_weed",
    label: "weed",
    accessKey: ItemAccessKey.NONE,
    canDelete: false,
    isIllegal: true,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.DRUGS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 40,
    canTrade: true,
  },

  /**
   * Detox pills — the cure for the addiction meter, sold in the EMS shop.
   * NOT illegal and NOT a drug: it has to stay buyable and carryable in the
   * open, which is why it is MEDICAL and carries no `isIllegal`.
   */
  item_detox_pills: {
    name: "item_detox_pills",
    label: "detox pills",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.MEDICAL,
    canUnStack: true,
    weight: 0.5,
    canStack: true,
    maxStack: 20,
    canTrade: true,
  },
  /** Rolling paper — the weed line's packaging. Sold by Vadim at $5. */
  item_rolling_paper: {
    name: "item_rolling_paper",
    label: "rolling paper",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  /** Finished product — gang bench, weed line. A joint, not a bag. */
  item_weed_joint: {
    name: "item_weed_joint",
    label: "weed joint",
    accessKey: ItemAccessKey.NONE,
    canDelete: false,
    isIllegal: true,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.DRUGS,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },

  item_battery: {
    name: "item_battery",
    label: "battery",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.PARTS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_engine_oil: {
    name: "item_engine_oil",
    label: "Engine Oil",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: true,
    category: ItemCategory.PARTS,
    canUnStack: true,
    weight: 1.5,
    canStack: true,
    maxStack: 10,
    canTrade: true,
  },
  item_car_battery: {
    name: "item_car_battery",
    label: "Car Battery",
    accessKey: ItemAccessKey.NONE,
    canUSE: true,
    canDrop: true,
    category: ItemCategory.PARTS,
    canUnStack: true,
    weight: 4,
    canStack: true,
    maxStack: 5,
    canTrade: true,
  },
  item_empty_plastic_pack: {
    name: "item_empty_plastic_pack",
    label: "empty plastic pack",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.PARTS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },
  item_gun_powder: {
    name: "item_gun_powder",
    label: "gun powder",
    accessKey: ItemAccessKey.NONE,
    isIllegal: true,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 30,
    canTrade: true,
  },


  item_lock_pick: {
    name: "item_lock_pick",
    label: "Lock Pick",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: true,
    isIllegal: true,
    weight: 1,
    canStack: true,
    maxStack: 10,
    canTrade: true,
  },

  // --- ATM robbery kit (features/atm-robbery) ---------------------------
  // The screwdriver opens the faceplate and is NEVER consumed; the chip does
  // the hack and is consumed the moment stage 2 completes.

  item_screwdriver: {
    name: "item_screwdriver",
    label: "Screwdriver",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 5,
    canTrade: true,
  },

  // --- SIM card (features/phone-system) ---------------------------------
  // NOT AN INVENTORY ITEM. It is listed here only because the shop UI reads
  // itemsProperties for a row's category, icon and stack size — buying it is
  // intercepted in BuyService (high-roleplay-v1), which assigns the character
  // a new 8-digit phone number instead of creating anything. It is
  // deliberately ABSENT from the gamemode's own itemProperties.ts, so there is
  // no way for it to end up in an inventory even if a call site slipped
  // through.
  item_sim_card: {
    name: "item_sim_card",
    label: "SIM Card",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    weight: 0,
    canStack: false,
    maxStack: 1,
    canTrade: false,
  },

  // Copied 1:1 from the gamemode catalogue
  // (server/high-roleplay/inventory/itemProperties.ts). Both are craftable on
  // the gang weapon bench but had never been given properties here, so the live
  // economyConfig shipped two recipes the shop UI had no weight or stack limit
  // for. checkItemCoverage now enforces this.
  item_train_bomb: {
    name: "item_train_bomb",
    label: "Breaching Charge",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: true,
    isIllegal: true,
    weight: 4,
    canStack: true,
    maxStack: 3,
    canTrade: true,
  },

  item_c4: {
    name: "item_c4",
    label: "C4 Explosive",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: true,
    isIllegal: true,
    weight: 6,
    canStack: true,
    maxStack: 2,
    canTrade: true,
  },

  item_atm_hack_chip: {
    name: "item_atm_hack_chip",
    label: "Hacking Chip",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: true,
    isIllegal: true,
    weight: 1,
    canStack: true,
    maxStack: 10,
    canTrade: true,
  },


  item_sulfuric_acid: {
    name: "item_sulfuric_acid",
    label: "sulfuric acid",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 2,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // JOB SPECS PACK (JOB_SPECS/) — Lumberjack, Mushroom Picker, Stonemason,
  // Hunter. Every entry here is mirrored by hand in the gamemode's own
  // catalog, server/high-roleplay/inventory/itemProperties.ts — that file is
  // the one grantStackableItem validates against, so an item missing there
  // throws on the very first harvest even though it is present here.
  // ═══════════════════════════════════════════════════════════════════════

  // ── Lumberjack (JOB_SPECS/05-Lumberjack.md) ──────────────────────────────
  item_log_pine: {
    name: "item_log_pine",
    label: "Pine Log",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 3,
    canStack: true,
    maxStack: 10, // [MANUAL] + [OBSERVED 102635] — 10 per cell
    canTrade: true,
  },
  item_log_oak: {
    name: "item_log_oak",
    label: "Oak Log",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 3,
    canStack: true,
    maxStack: 10,
    canTrade: true,
  },
  item_log_birch: {
    name: "item_log_birch",
    label: "Birch Log",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 3,
    canStack: true,
    maxStack: 10,
    canTrade: true,
  },
  item_log_maple: {
    name: "item_log_maple",
    label: "Maple Log",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 3,
    canStack: true,
    maxStack: 10,
    canTrade: true,
  },
  item_axe_common: {
    name: "item_axe_common",
    label: "Common Axe",
    accessKey: ItemAccessKey.TOOL,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    durability: 200, // [MANUAL] Description.txt — 200 trees
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  // ── Mushroom Picker (JOB_SPECS/06-MushroomPicker.md) ─────────────────────
  item_shovel: {
    name: "item_shovel",
    label: "Shovel",
    accessKey: ItemAccessKey.TOOL,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    durability: 200,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_mushroom_champignon: {
    name: "item_mushroom_champignon",
    label: "Champignon",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },
  item_mushroom_oyster: {
    name: "item_mushroom_oyster",
    label: "Oyster Mushroom",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },
  item_mushroom_honey: {
    name: "item_mushroom_honey",
    label: "Honey Fungus",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },
  item_mushroom_flyagaric: {
    name: "item_mushroom_flyagaric",
    label: "Fly Agaric",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },
  item_mushroom_chanterelle: {
    name: "item_mushroom_chanterelle",
    label: "Chanterelle",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },
  item_mushroom_russula: {
    name: "item_mushroom_russula",
    label: "Green Russula",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },
  item_mushroom_king: {
    name: "item_mushroom_king",
    label: "King Mushroom",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.2,
    canStack: true,
    maxStack: 25,
    canTrade: true,
  },

  // ── Stonemason (JOB_SPECS/07-Stonemason.md) ──────────────────────────────
  item_pickaxe_stone_1: {
    name: "item_pickaxe_stone_1",
    label: "Ordinary Pickaxe",
    accessKey: ItemAccessKey.TOOL,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    durability: 200,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_pickaxe_stone_2: {
    name: "item_pickaxe_stone_2",
    label: "Improved Pickaxe",
    accessKey: ItemAccessKey.TOOL,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    durability: 200,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_pickaxe_stone_3: {
    name: "item_pickaxe_stone_3",
    label: "Best Pickaxe",
    accessKey: ItemAccessKey.TOOL,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    durability: 200,
    weight: 2,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  // maxStack 500, NOT the 100 the refinery ores use: one 1500-unit sales window
  // has to fit in ~3 of a player's 30 slots or the bag-full branch fires
  // constantly, and a real player was observed holding 507 kg of iron.
  item_metal_iron: {
    name: "item_metal_iron",
    label: "Iron",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 500,
    canTrade: true,
  },
  item_metal_copper: {
    name: "item_metal_copper",
    label: "Copper",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 500,
    canTrade: true,
  },
  item_metal_silver: {
    name: "item_metal_silver",
    label: "Silver",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.02,
    canStack: true,
    maxStack: 500,
    canTrade: true,
  },
  item_metal_gold: {
    name: "item_metal_gold",
    label: "Gold",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.02,
    canStack: true,
    maxStack: 500,
    canTrade: true,
  },
  item_metal_diamond: {
    name: "item_metal_diamond",
    label: "Diamond",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.05,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },

  // ── Hunter (JOB_SPECS/08-Hunter.md) ──────────────────────────────────────
  // 32 pelts + 8 meats, built above from the JOBS/HUNTER.js tables.
  ...hunterPeltItems,
  ...hunterMeatItems,
  item_weapon_musket: {
    name: "item_weapon_musket",
    label: "Musket",
    accessKey: ItemAccessKey.PRIMARY_WEAPON,
    canDelete: false,
    isIllegal: false,
    category: ItemCategory.WEAPON,
    durability: 100,
    canUSE: false,
    canDrop: false,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  // NOTE: no `item_bullet_musket`. The musket loads standard
  // `item_bullet_shotgun` from the shared SHOTGUN_AMMO pool.
  // ═══════════════════════════════════════════════════════════════════════
  // JOB SPECS PACK 2 (JOB_SPECS/_integration/) — Electrician, Aquanaut,
  // Fisherman. Garbage Collector, Collector and Mechanic add NO item.
  // Same rule as the block above: every entry here is mirrored BY HAND in
  // server/high-roleplay/inventory/itemProperties.ts, which is the catalog
  // itemManager.newItem() validates against — an item present only here throws
  // on the first grant, silently (§13.1).
  // ═══════════════════════════════════════════════════════════════════════

  // ── Electrician (JOB_SPECS/10-Electrician.md) ────────────────────────────
  // Salvaged parts. Sell prices live in JOBS/ELECTRIC.js `salvage`.
  item_electro_diode: {
    name: "item_electro_diode",
    label: "Diode",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.TOOLS,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 40,
    canTrade: true,
  },
  item_electro_transistor: {
    name: "item_electro_transistor",
    label: "Transistor",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.TOOLS,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 40,
    canTrade: true,
  },
  item_electro_microchip: {
    name: "item_electro_microchip",
    label: "Microcircuit",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.TOOLS,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 20,
    canTrade: true,
  },

  // ── Aquanaut (JOB_SPECS/13-Aquanaut.md) ──────────────────────────────────
  // Bonus finds from the crates. Sell prices live in JOBS/AQUANAUT.js `finds`.
  item_sea_rapan: {
    name: "item_sea_rapan",
    label: "Rapan Shell",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.2,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },
  item_sea_starfish: {
    name: "item_sea_starfish",
    label: "Starfish",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.2,
    canStack: true,
    maxStack: 100,
    canTrade: true,
  },
  item_sea_pearl: {
    name: "item_sea_pearl",
    label: "Pearl",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.05,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },

  // ── Fisherman (JOB_SPECS/14-Fisherman.md) ────────────────────────────────
  // The rod. TOOLS/TOOL with `durability`, exactly like item_axe_common and the
  // pickaxes above: 200 catches per rod. Buyable in SHOPS/SUPERMARKET.js — that
  // row IS the job's hire step, there is no NPC (§13.3).
  item_fishing_rod: {
    name: "item_fishing_rod",
    // Label/canUSE/weight below match the LIVE gamemode catalogue
    // (server/high-roleplay/inventory/itemProperties.ts). canUSE MUST stay true
    // — false is what made the rod unequippable, and regenerating used to
    // silently revert it.
    label: "Regular Fishing Rod",
    accessKey: ItemAccessKey.TOOL,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    durability: 200, // [MANUAL] Description.txt L38 — 200 catches
    weight: 2.5,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  // Bait. accessKey NONE and canUSE false is what MECHANICALLY enforces
  // [MANUAL] Description.txt L34 — "the bait does not appear in quick access and
  // is only stored in the inventory". Do NOT give it an accessKey.
  item_fish_bait: {
    name: "item_fish_bait",
    label: "Fish Bait",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.05,
    canStack: true,
    maxStack: 500,
    canTrade: true,
  },
  item_fish_bait_improved: {
    name: "item_fish_bait_improved",
    label: "Improved Fish Bait",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.05,
    canStack: true,
    maxStack: 500,
    canTrade: true,
  },
  item_fish_bait_extra: {
    name: "item_fish_bait_extra",
    label: "Extra Fish Bait",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.05,
    canStack: true,
    maxStack: 500,
    canTrade: true,
  },

  // FISH ARE STORED IN GRAMS. One stack per species; `stack` IS the gram count.
  // maxStack 50000 = 50 kg per slot and is LOAD-BEARING, not a typo: the
  // server's hasRoomForCatch() refuses a cast when no unlocked species has room
  // for its tier's maximum weight, so a small maxStack makes the job refuse to
  // cast. weight 0.001 makes one gram of fish weigh one gram.
  // All fourteen are the same shape — only `name` and `label` change.
  item_fish_herring:     { name: "item_fish_herring",     label: "Herring",     accessKey: ItemAccessKey.NONE, canUSE: false, canDrop: true, category: ItemCategory.MATERIALS, canUnStack: true, weight: 0.001, canStack: true, maxStack: 50000, canTrade: true },
  item_fish_mullet:      { name: "item_fish_mullet",      label: "Mullet",      accessKey: ItemAccessKey.NONE, canUSE: false, canDrop: true, category: ItemCategory.MATERIALS, canUnStack: true, weight: 0.001, canStack: true, maxStack: 50000, canTrade: true },
  item_fish_mackerel:    { name: "item_fish_mackerel",    label: "Mackerel",    accessKey: ItemAccessKey.NONE, canUSE: false, canDrop: true, category: ItemCategory.MATERIALS, canUnStack: true, weight: 0.001, canStack: true, maxStack: 50000, canTrade: true },
  // Perch and Flounder carry the LIVE weight/maxStack (2 kg, 20 per stack) —
  // the 0.001/50000 placeholder the rest of this block uses was never what the
  // gamemode shipped, and regenerating used to overwrite the real values.
  item_fish_perch:       { name: "item_fish_perch",       label: "Perch",       accessKey: ItemAccessKey.NONE, canUSE: false, canDrop: true, category: ItemCategory.MATERIALS, canUnStack: true, weight: 2,     canStack: true, maxStack: 20,    canTrade: true },
  item_fish_cod:         { name: "item_fish_cod",         label: "Cod",         accessKey: ItemAccessKey.NONE, canUSE: false, canDrop: true, category: ItemCategory.MATERIALS, canUnStack: true, weight: 0.001, canStack: true, maxStack: 50000, canTrade: true },
  item_fish_pink_salmon: { name: "item_fish_pink_salmon", label: "Pink Salmon", accessKey: ItemAccessKey.NONE, canUSE: false, canDrop: true, category: ItemCategory.MATERIALS, canUnStack: true, weight: 0.001, canStack: true, maxStack: 50000, canTrade: true },
  item_fish_sea_bass:    { name: "item_fish_sea_bass",    label: "Sea Bass",    accessKey: ItemAccessKey.NONE, canUSE: false, canDrop: true, category: ItemCategory.MATERIALS, canUnStack: true, weight: 0.001, canStack: true, maxStack: 50000, canTrade: true },
  item_fish_tuna:        { name: "item_fish_tuna",        label: "Tuna",        accessKey: ItemAccessKey.NONE, canUSE: false, canDrop: true, category: ItemCategory.MATERIALS, canUnStack: true, weight: 0.001, canStack: true, maxStack: 50000, canTrade: true },
  item_fish_dorado:      { name: "item_fish_dorado",      label: "Dorado",      accessKey: ItemAccessKey.NONE, canUSE: false, canDrop: true, category: ItemCategory.MATERIALS, canUnStack: true, weight: 0.001, canStack: true, maxStack: 50000, canTrade: true },
  item_fish_flounder:    { name: "item_fish_flounder",    label: "Flounder",    accessKey: ItemAccessKey.NONE, canUSE: false, canDrop: true, category: ItemCategory.MATERIALS, canUnStack: true, weight: 2,     canStack: true, maxStack: 20,    canTrade: true },
  item_fish_trout:       { name: "item_fish_trout",       label: "Trout",       accessKey: ItemAccessKey.NONE, canUSE: false, canDrop: true, category: ItemCategory.MATERIALS, canUnStack: true, weight: 0.001, canStack: true, maxStack: 50000, canTrade: true },
  item_fish_pufferfish:  { name: "item_fish_pufferfish",  label: "Pufferfish",  accessKey: ItemAccessKey.NONE, canUSE: false, canDrop: true, category: ItemCategory.MATERIALS, canUnStack: true, weight: 0.001, canStack: true, maxStack: 50000, canTrade: true },
  item_fish_shark:       { name: "item_fish_shark",       label: "Shark",       accessKey: ItemAccessKey.NONE, canUSE: false, canDrop: true, category: ItemCategory.MATERIALS, canUnStack: true, weight: 0.001, canStack: true, maxStack: 50000, canTrade: true },
  item_fish_stingray:    { name: "item_fish_stingray",    label: "Stingray",    accessKey: ItemAccessKey.NONE, canUSE: false, canDrop: true, category: ItemCategory.MATERIALS, canUnStack: true, weight: 0.001, canStack: true, maxStack: 50000, canTrade: true },


  // ══════════════════════════════════════════════════════════════════════
  // RECOVERED ITEMS — copied 1:1 from the gamemode catalogue
  // (server/high-roleplay/inventory/itemProperties.ts), which is the real
  // source of truth: the backend seeds its item definitions from THAT file,
  // never from this one. What this file feeds is `itemsProperties` in
  // economyConfig, which high-ui's SHOP screens read for weight, category
  // and stack limits.
  //
  // Every one of these was already sold or crafted somewhere in the generated
  // config while having NO properties entry — so the shop cart had no weight,
  // no category filter and no stack cap for them. `npm run generate` now fails
  // loudly if that ever happens again (see generate_economy_config.js).
  // ══════════════════════════════════════════════════════════════════════

  // JUNK — the junk job's output. 3 of these are also the ATM hacking chip's
  // materials, so the gang bench lists a recipe whose inputs had no properties.
  item_junk_bent_metal_pipe: {
    name: "item_junk_bent_metal_pipe",
    label: "Bent Metal Pipe",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_junk_broken_phone: {
    name: "item_junk_broken_phone",
    label: "Broken Phone",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.2,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_junk_car_battery: {
    name: "item_junk_car_battery",
    label: "DAMAGED CAR BATTERY",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 3,
    canStack: true,
    maxStack: 10,
    canTrade: true,
  },
  item_junk_circuit_board: {
    name: "item_junk_circuit_board",
    label: "Old Circuit Board",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.5,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_junk_crashed_bottle: {
    name: "item_junk_crashed_bottle",
    label: "Crashed Bottle",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.2,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_junk_oil_can: {
    name: "item_junk_oil_can",
    label: "Oil Can",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.5,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_junk_rusty_usb: {
    name: "item_junk_rusty_usb",
    label: "Rusty USB Drive",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.1,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },
  item_junk_torn_shoe: {
    name: "item_junk_torn_shoe",
    label: "Torn Shoe",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.3,
    canStack: true,
    maxStack: 50,
    canTrade: true,
  },

  // VESTS — gang (0) and the marked state plate carriers (18-25).
  item_vest_0: {
    name: "item_vest_0",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_18: {
    name: "item_vest_18",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    placeIn: "INVENTORY",
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_19: {
    name: "item_vest_19",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    placeIn: "INVENTORY",
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_20: {
    name: "item_vest_20",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    placeIn: "INVENTORY",
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_21: {
    name: "item_vest_21",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    placeIn: "INVENTORY",
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_22: {
    name: "item_vest_22",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    placeIn: "INVENTORY",
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_23: {
    name: "item_vest_23",
    label: "vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    placeIn: "INVENTORY",
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_24: {
    name: "item_vest_24",
    label: "fib vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    placeIn: "INVENTORY",
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },
  item_vest_25: {
    name: "item_vest_25",
    label: "sheriff vest",
    accessKey: ItemAccessKey.VEST,
    canUSE: false,
    canDrop: false,
    placeIn: "INVENTORY",
    category: ItemCategory.VEST,
    canUnStack: false,
    weight: 0.1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
    durability: 100,
  },

  // GEAR — crafted at the state shared bench.
  item_body_cam: {
    name: "item_body_cam",
    label: "Body Camera",
    accessKey: ItemAccessKey.NONE,
    durability: 100,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    weight: 1,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_drone: {
    name: "item_drone",
    label: "Drone",
    accessKey: ItemAccessKey.NONE,
    durability: 100,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    weight: 3,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },

  // FISHING — the LIVE fishing job reads its fish list and its three rod tiers from
  // the gamemode (shared/jobs/fishing.shared.ts), NOT from this file. These entries
  // exist so the shop/inventory UI knows their weight, category and stack size.
  item_fishing_rod_good: {
    name: "item_fishing_rod_good",
    label: "Good Fishing Rod",
    accessKey: ItemAccessKey.TOOL,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    canDelete: true,
    isIllegal: false,
    weight: 2.5,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_fishing_rod_excellent: {
    name: "item_fishing_rod_excellent",
    label: "High-Quality Fishing Rod",
    accessKey: ItemAccessKey.TOOL,
    canUSE: true,
    canDrop: false,
    category: ItemCategory.TOOLS,
    canUnStack: false,
    canDelete: true,
    isIllegal: false,
    weight: 2.5,
    canStack: false,
    maxStack: 1,
    canTrade: true,
  },
  item_fish_roach: {
    name: "item_fish_roach",
    label: "Roach",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    canDelete: true,
    isIllegal: false,
    weight: 2,
    canStack: true,
    maxStack: 20,
    canTrade: true,
  },
  item_fish_pike: {
    name: "item_fish_pike",
    label: "Pike",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    canDelete: true,
    isIllegal: false,
    weight: 2,
    canStack: true,
    maxStack: 20,
    canTrade: true,
  },
  item_fish_zander: {
    name: "item_fish_zander",
    label: "Zander",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    canDelete: true,
    isIllegal: false,
    weight: 2,
    canStack: true,
    maxStack: 20,
    canTrade: true,
  },
  item_fish_carp: {
    name: "item_fish_carp",
    label: "Carp",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    canDelete: true,
    isIllegal: false,
    weight: 2,
    canStack: true,
    maxStack: 20,
    canTrade: true,
  },
  item_fish_coho_salmon: {
    name: "item_fish_coho_salmon",
    label: "Coho Salmon",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    canDelete: true,
    isIllegal: false,
    weight: 2,
    canStack: true,
    maxStack: 20,
    canTrade: true,
  },
  item_fish_salmon: {
    name: "item_fish_salmon",
    label: "Salmon",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    canDelete: true,
    isIllegal: false,
    weight: 2,
    canStack: true,
    maxStack: 20,
    canTrade: true,
  },
  item_fish_sturgeon: {
    name: "item_fish_sturgeon",
    label: "Sturgeon",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    canDelete: true,
    isIllegal: false,
    weight: 2,
    canStack: true,
    maxStack: 20,
    canTrade: true,
  },
  item_fish_fugu: {
    name: "item_fish_fugu",
    label: "Fugu",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    canDelete: true,
    isIllegal: false,
    weight: 2,
    canStack: true,
    maxStack: 20,
    canTrade: true,
  },

  // LEGACY — present in the deployed economyConfig but NOT in the gamemode
  // catalogue, so the server cannot actually create this item. Kept so a
  // regenerate never drops it; retire it deliberately if it is truly dead.
  item_meat_hen: {
    name: "item_meat_hen",
    label: "Chicken meat",
    accessKey: ItemAccessKey.NONE,
    canUSE: false,
    canDrop: true,
    category: ItemCategory.MATERIALS,
    canUnStack: true,
    weight: 0.8,
    canStack: true,
    maxStack: 20,
    canTrade: true,
  },

  // ...add more items here
};
