const playerAvaregeIncome = 10000;
const hardLvl = 1
const calcPrice = (hourToGain) => {
    const price = playerAvaregeIncome * hourToGain;
    // Round the price to the nearest 250, 500, 750, or 000
    const remainder = price % 250;
    const roundedPrice = price - remainder;

    return Math.floor(roundedPrice * hardLvl);
}

export const carV3 =[
    
        { Model: "panto", Name: "Panto", Class: "COMPACT", Price: calcPrice(5.000), Brand: "Benefactor" },
        { Model: "asbo", Name: "Asbo", Class: "COMPACT", Price: calcPrice(5.810), Brand: "Maxwell" },
        { Model: "issi3", Name: "Issi Classic", Class: "COMPACT", Price: calcPrice(6.619), Brand: "Weeny" },
        { Model: "issi2", Name: "Issi", Class: "COMPACT", Price: calcPrice(7.429), Brand: "Weeny" },
        { Model: "club", Name: "Club", Class: "COMPACT", Price: calcPrice(8.238), Brand: "BF" },
        { Model: "dilettante", Name: "Dilettante", Class: "COMPACT", Price: calcPrice(9.048), Brand: "Karin" },
        { Model: "weevil", Name: "Weevil", Class: "COMPACT", Price: calcPrice(9.857), Brand: "BF" },
        { Model: "rhapsody", Name: "Rhapsody", Class: "COMPACT", Price: calcPrice(10.667), Brand: "Declasse" },
        { Model: "kanjo", Name: "Blista Kanjo", Class: "COMPACT", Price: calcPrice(11.476), Brand: "Dinka" },
        { Model: "brioso2", Name: "Brioso 300", Class: "COMPACT", Price: calcPrice(12.286), Brand: "Grotti" },
        
        { Model: "blista", Name: "Blista", Class: "COMPACT", Price: calcPrice(13.905), Brand: "Dinka" },
        { Model: "blista3", Name: "Blista Go Go Monkey", Class: "COMPACT", Price: calcPrice(14.714), Brand: "Dinka" },
        { Model: "blista2", Name: "Blista Compact", Class: "COMPACT", Price: calcPrice(15.524), Brand: "Dinka" },
        { Model: "brioso", Name: "Brioso R/A", Class: "COMPACT", Price: calcPrice(16.333), Brand: "Grotti" },
        { Model: "boor", Name: "Boor", Class: "COMPACT", Price: calcPrice(17.143), Brand: "Karin" },
        { Model: "prairie", Name: "Prairie", Class: "COMPACT", Price: calcPrice(17.952), Brand: "Bollokan" },
        { Model: "issi7", Name: "Issi Sport", Class: "COMPACT", Price: calcPrice(21.190), Brand: "Weeny" },
        { Model: "brioso3", Name: "Brioso 300 Widebody", Class: "COMPACT", Price: calcPrice(22.000), Brand: "Grotti" },
    


        
            { Model: "asea", Name: "Asea", Class: "SEDAN", Price: calcPrice(8.000), Brand: "Declasse" },
            { Model: "glendale", Name: "Glendale", Class: "SEDAN", Price: calcPrice(8.838), Brand: "Benefactor" },
            { Model: "warrener", Name: "Warrener", Class: "SEDAN", Price: calcPrice(9.676), Brand: "Vulcar" },
            { Model: "emperor", Name: "Emperor", Class: "SEDAN", Price: calcPrice(10.514), Brand: "Albany" },
            { Model: "ingot", Name: "Ingot", Class: "SEDAN", Price: calcPrice(11.351), Brand: "Vulcar" },
            { Model: "primo", Name: "Primo", Class: "SEDAN", Price: calcPrice(12.189), Brand: "Albany" },
            { Model: "regina", Name: "Regina", Class: "SEDAN", Price: calcPrice(13.027), Brand: "Dundreary" },
            { Model: "washington", Name: "Washington", Class: "SEDAN", Price: calcPrice(13.865), Brand: "Albany" },
            { Model: "asterope", Name: "Asterope", Class: "SEDAN", Price: calcPrice(14.703), Brand: "Karin" },
            { Model: "intruder", Name: "Intruder", Class: "SEDAN", Price: calcPrice(15.541), Brand: "Karin" },
            { Model: "glendale2", Name: "Glendale Custom", Class: "SEDAN", Price: calcPrice(16.378), Brand: "Benefactor" },
            { Model: "premier", Name: "Premier", Class: "SEDAN", Price: calcPrice(17.216), Brand: "Declasse" },
            { Model: "primo2", Name: "Primo Custom", Class: "SEDAN", Price: calcPrice(18.054), Brand: "Albany" },
            { Model: "stratum", Name: "Stratum", Class: "SEDAN", Price: calcPrice(18.892), Brand: "Zirconium" },
            { Model: "schafter2", Name: "Schafter", Class: "SEDAN", Price: calcPrice(19.730), Brand: "Benefactor" },
            { Model: "eudora", Name: "Eudora", Class: "SEDAN", Price: calcPrice(20.568), Brand: "Willard" },
            { Model: "SUPERd", Name: "SUPER Diamond", Class: "SEDAN", Price: calcPrice(21.405), Brand: "Enus" },
            { Model: "stanier", Name: "Stanier", Class: "SEDAN", Price: calcPrice(22.243), Brand: "Vapid" },
            { Model: "stretch", Name: "Stretch", Class: "SEDAN", Price: calcPrice(29.081), Brand: "Dundreary" },
            { Model: "fugitive", Name: "Fugitive", Class: "SEDAN", Price: calcPrice(23.919), Brand: "Cheval" },
            { Model: "surge", Name: "Surge", Class: "SEDAN", Price: calcPrice(24.757), Brand: "Cheval" },
            { Model: "cog55", Name: "Cognoscenti 55", Class: "SEDAN", Price: calcPrice(25.595), Brand: "Enus" },
            { Model: "oracle", Name: "Oracle", Class: "SEDAN", Price: calcPrice(26.432), Brand: "Übermacht" },
            { Model: "tailgater", Name: "Tailgater", Class: "SEDAN", Price: calcPrice(27.270), Brand: "Obey" },
            { Model: "cognoscenti", Name: "Cognoscenti", Class: "SEDAN", Price: calcPrice(28.108), Brand: "Enus" },
            { Model: "stafford", Name: "Stafford", Class: "SEDAN", Price: calcPrice(29.784), Brand: "Enus" },
            { Model: "warrener2", Name: "Warrener HKR", Class: "SEDAN", Price: calcPrice(21.622), Brand: "Vulcar" },
            { Model: "tailgater2", Name: "Tailgater S", Class: "SEDAN", Price: calcPrice(31.459), Brand: "Obey" },
            { Model: "rhinehart", Name: "Rhinehart", Class: "SEDAN", Price: calcPrice(32.297), Brand: "Übermacht" },
            { Model: "cinquemila", Name: "Lampadati", Class: "SEDAN", Price: calcPrice(33.135), Brand: "Cinquemila" },
            { Model: "baller7", Name: "Baller ST", Class: "SEDAN", Price: calcPrice(33.973), Brand: "Gallivanter" },
            { Model: "astron", Name: "Astron", Class: "SEDAN", Price: calcPrice(34.811), Brand: "Pfister" },
            { Model: "iwagen", Name: "Obey", Class: "SEDAN", Price: calcPrice(35.649), Brand: "I-Wagen" },
            { Model: "asterope2", Name: "Asterope GZ", Class: "SEDAN", Price: calcPrice(36.486), Brand: "Karin" },
            // { Model: "jubilee", Name: "Jubilee", Class: "SEDAN", Price: calcPrice(37.324), Brand: "Enus" },
            { Model: "deity", Name: "Deity", Class: "SEDAN", Price: calcPrice(40.162), Brand: "Enus" },
            { Model: "impaler5", Name: "Impaler SZ", Class: "SEDAN", Price: calcPrice(39.000), Brand: "Declasse" },
        




            
                { Model: "landstalker", Name: "Landstalker", Class: "SUV", Price: calcPrice(8.000), Brand: "Dundreary" },
                { Model: "rocoto", Name: "Rocoto", Class: "SUV", Price: calcPrice(8.838), Brand: "Obey" },
                { Model: "seminole2", Name: "Seminole Frontier", Class: "SUV", Price: calcPrice(9.676), Brand: "Canis" },
                { Model: "cavalcade", Name: "Cavalcade", Class: "SUV", Price: calcPrice(10.514), Brand: "Albany" },
                { Model: "baller2", Name: "Baller II", Class: "SUV", Price: calcPrice(11.351), Brand: "Gallivanter" },
                { Model: "baller3", Name: "Baller LE", Class: "SUV", Price: calcPrice(12.189), Brand: "Gallivanter" },
                { Model: "cavalcade2", Name: "Cavalcade II", Class: "SUV", Price: calcPrice(13.027), Brand: "Albany" },
                { Model: "xls", Name: "XLS", Class: "SUV", Price: calcPrice(13.865), Brand: "Benefactor" },
                { Model: "radi", Name: "Radius", Class: "SUV", Price: calcPrice(14.703), Brand: "Vapid" },
                { Model: "fq2", Name: "FQ2", Class: "SUV", Price: calcPrice(15.541), Brand: "Fathom" },
                { Model: "bjxl", Name: "BeeJay XL", Class: "SUV", Price: calcPrice(16.378), Brand: "Karin" },
                { Model: "dubsta", Name: "Dubsta", Class: "SUV", Price: calcPrice(17.216), Brand: "Benefactor" },
                { Model: "dubsta2", Name: "Dubsta Luxury", Class: "SUV", Price: calcPrice(18.054), Brand: "Benefactor" },
                { Model: "habanero", Name: "Habanero", Class: "SUV", Price: calcPrice(18.892), Brand: "Emperor" },
                { Model: "seminole", Name: "Seminole", Class: "SUV", Price: calcPrice(19.730), Brand: "Canis" },
                { Model: "patriot", Name: "Patriot", Class: "SUV", Price: calcPrice(20.568), Brand: "Mammoth" },
                { Model: "patriot2", Name: "Patriot Stretch", Class: "SUV", Price: calcPrice(25.405), Brand: "Mammoth" },
                { Model: "rebla", Name: "Rebla GTS", Class: "SUV", Price: calcPrice(22.243), Brand: "Übermacht" },
                { Model: "baller", Name: "Baller", Class: "SUV", Price: calcPrice(23.081), Brand: "Gallivanter" },
                { Model: "granger", Name: "Granger", Class: "SUV", Price: calcPrice(23.919), Brand: "Declasse" },
                { Model: "huntley", Name: "Huntley S", Class: "SUV", Price: calcPrice(24.757), Brand: "Enus" },
                { Model: "gresley", Name: "Gresley", Class: "SUV", Price: calcPrice(25.595), Brand: "Bravado" },
                { Model: "landstalker2", Name: "Landstalker XL", Class: "SUV", Price: calcPrice(26.432), Brand: "Dundreary" },
                { Model: "baller4", Name: "Baller LE LWB", Class: "SUV", Price: calcPrice(27.270), Brand: "Gallivanter" },
                { Model: "contender", Name: "Contender", Class: "SUV", Price: calcPrice(28.108), Brand: "Vapid" },
                { Model: "serrano", Name: "Serrano", Class: "SUV", Price: calcPrice(28.946), Brand: "Benefactor" },
                { Model: "toros", Name: "Toros", Class: "SUV", Price: calcPrice(29.784), Brand: "Pegassi" },
                { Model: "novak", Name: "Novak", Class: "SUV", Price: calcPrice(30.622), Brand: "Lampadati" },

                
                { Model: "dorado", Name: "Dorado", Class: "SUV", Price: calcPrice(33.135), Brand: "Bravado" },
                { Model: "castigator", Name: "Castigator", Class: "SUV", Price: calcPrice(33.973), Brand: "Canis" },
                { Model: "vivanite", Name: "Vivanite", Class: "SUV", Price: calcPrice(34.811), Brand: "Karin" },
                { Model: "cavalcade3", Name: "Cavalcade XL", Class: "SUV", Price: calcPrice(35.649), Brand: "Albany" },
                { Model: "baller8", Name: "Baller ST-D", Class: "SUV", Price: calcPrice(36.486), Brand: "Gallivanter" },
                { Model: "aleutian", Name: "Aleutian", Class: "SUV", Price: calcPrice(37.324), Brand: "Vapid" },
                { Model: "granger2", Name: "Granger 3600LX", Class: "SUV", Price: calcPrice(38.162), Brand: "Declasse" },
             




                
                    { Model: "tahoma", Name: "Tahoma Coupe", Class: "COUPE", Price: calcPrice(7.000), Brand: "Declasse" },
                    { Model: "futo", Name: "Futo", Class: "COUPE", Price: calcPrice(13.476), Brand: "Karin" },
                    { Model: "jackal", Name: "Jackal", Class: "COUPE", Price: calcPrice(13.002), Brand: "Ocelot" },
                    { Model: "broadway", Name: "Broadway", Class: "COUPE", Price: calcPrice(11.429), Brand: "Classique" },
                    { Model: "zion", Name: "Zion", Class: "COUPE", Price: calcPrice(12.905), Brand: "Übermacht" },
                    { Model: "oracle2", Name: "Oracle XS", Class: "COUPE", Price: calcPrice(15.857), Brand: "Übermacht" },
                    { Model: "zion2", Name: "Zion Cabrio", Class: "COUPE", Price: calcPrice(17.333), Brand: "Übermacht" },
                    { Model: "cogcabrio", Name: "Cognoscenti Cabrio", Class: "COUPE", Price: calcPrice(18.810), Brand: "Enus" },
                    { Model: "sentinel", Name: "Sentinel", Class: "COUPE", Price: calcPrice(20.286), Brand: "Übermacht" },
                    { Model: "felon", Name: "Felon", Class: "COUPE", Price: calcPrice(21.762), Brand: "Lampadati" },
                    { Model: "f620", Name: "F620", Class: "COUPE", Price: calcPrice(37.238), Brand: "Ocelot" },
                    { Model: "sentinel2", Name: "Sentinel XS", Class: "COUPE", Price: calcPrice(24.714), Brand: "Übermacht" },
                    { Model: "felon2", Name: "Felon GT", Class: "COUPE", Price: calcPrice(27.667), Brand: "Lampadati" },
                    { Model: "exemplar", Name: "Exemplar", Class: "COUPE", Price: calcPrice(29.143), Brand: "Dewbauchee" },
                    { Model: "sentinel3", Name: "Sentinel Classic", Class: "COUPE", Price: calcPrice(30.619), Brand: "Übermacht" },
                    { Model: "postlude", Name: "Postlude", Class: "COUPE", Price: calcPrice(10.095), Brand: "Dinka" },
                    { Model: "kanjosj", Name: "Kanjo SJ", Class: "COUPE", Price: calcPrice(11.571), Brand: "Dinka" },
                    { Model: "previon", Name: "Previon", Class: "COUPE", Price: calcPrice(35.048), Brand: "Karin" },
                    { Model: "fr36", Name: "FR36", Class: "COUPE", Price: calcPrice(36.524), Brand: "Fathom" },
                    { Model: "champion", Name: "Champion", Class: "COUPE", Price: calcPrice(38.000), Brand: "Dewbauchee" },
                    { Model: "windsor", Name: "Windsor", Class: "COUPE", Price: calcPrice(39.381), Brand: "Enus" },
                    { Model: "windsor2", Name: "Windsor Drop", Class: "COUPE", Price: calcPrice(41.190), Brand: "Enus" },
                


                    
                        { Model: "chino", Name: "Chino", Class: "MUSCLE", Price: calcPrice(4.000), Brand: "Vapid" },
                        { Model: "chino2", Name: "Chino Luxe", Class: "MUSCLE", Price: calcPrice(4.542), Brand: "Vapid" },
                        { Model: "manana", Name: "Manana", Class: "MUSCLE", Price: calcPrice(5.083), Brand: "Albany" },
                        { Model: "voodoo", Name: "Voodoo", Class: "MUSCLE", Price: calcPrice(5.625), Brand: "Declasse" },
                        { Model: "faction", Name: "Faction", Class: "MUSCLE", Price: calcPrice(6.167), Brand: "Willard" },
                        { Model: "slamvan3", Name: "Slam Van Custom", Class: "MUSCLE", Price: calcPrice(6.708), Brand: "Vapid" },
                        { Model: "faction2", Name: "Faction Rider", Class: "MUSCLE", Price: calcPrice(7.250), Brand: "Willard" },
                        { Model: "yosemite", Name: "Yosemite", Class: "MUSCLE", Price: calcPrice(11.192), Brand: "Declasse" },
                        { Model: "clique", Name: "Clique", Class: "MUSCLE", Price: calcPrice(8.333), Brand: "Vapid" },
                        { Model: "picador", Name: "Picador", Class: "MUSCLE", Price: calcPrice(8.875), Brand: "Cheval" },
                        { Model: "ratloader2", Name: "Ratloader", Class: "MUSCLE", Price: calcPrice(9.417), Brand: "Ratloader2" },
                        { Model: "lurcher", Name: "Lurcher", Class: "MUSCLE", Price: calcPrice(9.958), Brand: "Bravado" },
                        { Model: "virgo3", Name: "Virgo Classic", Class: "MUSCLE", Price: calcPrice(10.500), Brand: "Dundreary" },
                        { Model: "virgo2", Name: "Virgo Custom Classic", Class: "MUSCLE", Price: calcPrice(11.042), Brand: "Dundreary" },
                        { Model: "virgo", Name: "Virgo", Class: "MUSCLE", Price: calcPrice(11.583), Brand: "Albany" },
                        { Model: "buccaneer", Name: "Buccaneer", Class: "MUSCLE", Price: calcPrice(12.125), Brand: "Albany" },
                        { Model: "sabregt", Name: "Sabre GT Turbo", Class: "MUSCLE", Price: calcPrice(12.667), Brand: "Declasse" },
                        { Model: "blade", Name: "Blade", Class: "MUSCLE", Price: calcPrice(13.208), Brand: "Vapid" },

                     
                        { Model: "slamvan", Name: "Slam Van", Class: "MUSCLE", Price: calcPrice(13.542), Brand: "Vapid" },


                        { Model: "manana2", Name: "Manana Custom", Class: "MUSCLE", Price: calcPrice(14.292), Brand: "Albany" },
                        { Model: "buccaneer2", Name: "Buccaneer Rider", Class: "MUSCLE", Price: calcPrice(14.833), Brand: "Albany" },
                        { Model: "tampa", Name: "Tampa", Class: "MUSCLE", Price: calcPrice(15.375), Brand: "Declasse" },
                        { Model: "sabregt2", Name: "Sabre GT Turbo Custom", Class: "MUSCLE", Price: calcPrice(15.917), Brand: "Declasse" },
                        { Model: "gauntlet", Name: "Gauntlet", Class: "MUSCLE", Price: calcPrice(16.458), Brand: "Bravado" },
                        { Model: "ruiner", Name: "Ruiner", Class: "MUSCLE", Price: calcPrice(17.000), Brand: "Imponte" },

                        { Model: "dukes", Name: "Dukes", Class: "MUSCLE", Price: calcPrice(17.750), Brand: "Imponte" },
                        { Model: "vamos", Name: "Vamos", Class: "MUSCLE", Price: calcPrice(18.083), Brand: "Declasse" },
                        { Model: "stalion", Name: "Stallion", Class: "MUSCLE", Price: calcPrice(18.625), Brand: "Declasse" },
                        { Model: "faction3", Name: "Faction Custom Donk", Class: "MUSCLE", Price: calcPrice(19.167), Brand: "Willard" },
                        { Model: "vigero", Name: "Vigero", Class: "MUSCLE", Price: calcPrice(19.708), Brand: "Declasse" },
                        { Model: "stalion2", Name: "Stallion Burgershot", Class: "MUSCLE", Price: calcPrice(20.250), Brand: "Declasse" },
                        { Model: "ellie", Name: "Ellie", Class: "MUSCLE", Price: calcPrice(20.792), Brand: "Vapid" },
                        { Model: "dukes3", Name: "Beater Dukes", Class: "MUSCLE", Price: calcPrice(21.333), Brand: "Imponte" },
                        { Model: "dominator2", Name: "Pißwasser Dominator", Class: "MUSCLE", Price: calcPrice(21.875), Brand: "Vapid" },

                        { Model: "yosemite2", Name: "Yosemite Drift", Class: "MUSCLE", Price: calcPrice(22.958), Brand: "Declasse" },
              
                        { Model: "dominator", Name: "Dominator", Class: "MUSCLE", Price: calcPrice(24.042), Brand: "Vapid" },
                        { Model: "phoenix", Name: "Phoenix", Class: "MUSCLE", Price: calcPrice(24.583), Brand: "Imponte" },
                        { Model: "deviant", Name: "Deviant", Class: "MUSCLE", Price: calcPrice(25.125), Brand: "Schyster" },
                        { Model: "dominator3", Name: "Dominator GTX", Class: "MUSCLE", Price: calcPrice(25.667), Brand: "Vapid" },
                        { Model: "nightshade", Name: "Nightshade", Class: "MUSCLE", Price: calcPrice(26.208), Brand: "Imponte" },
                        { Model: "gauntlet2", Name: "Redwood Gauntlet", Class: "MUSCLE", Price: calcPrice(26.750), Brand: "Bravado" },
                        { Model: "gauntlet3", Name: "Classic Gauntlet", Class: "MUSCLE", Price: calcPrice(27.292), Brand: "Bravado" },
                        { Model: "dominator8", Name: "Dominator GTT", Class: "MUSCLE", Price: calcPrice(27.833), Brand: "Vapid" },
                        { Model: "tampa2", Name: "Drift Tampa", Class: "MUSCLE", Price: calcPrice(28.375), Brand: "Declasse" },
                        { Model: "gauntlet4", Name: "Gauntlet Hellfire", Class: "MUSCLE", Price: calcPrice(28.917), Brand: "Bravado" },
                        { Model: "tulip", Name: "Tulip", Class: "MUSCLE", Price: calcPrice(29.458), Brand: "Declasse" },
                        { Model: "tulip2", Name: "Tulip M-100", Class: "MUSCLE", Price: calcPrice(19.000), Brand: "Declasse" },
                        { Model: "ruiner4", Name: "Ruiner ZZ-8", Class: "MUSCLE", Price: calcPrice(30.542), Brand: "Imponte" },
                        { Model: "hotknife", Name: "Hotknife", Class: "MUSCLE", Price: calcPrice(31.083), Brand: "Vapid" },
                        { Model: "slamvan2", Name: "Lost Slam Van", Class: "MUSCLE", Price: calcPrice(31.625), Brand: "Vapid" },
                        { Model: "hustler", Name: "Hustler", Class: "MUSCLE", Price: calcPrice(32.167), Brand: "Vapid" },
                        { Model: "impaler", Name: "Impaler", Class: "MUSCLE", Price: calcPrice(32.708), Brand: "Vapid" },
         
          
                        { Model: "weevil2", Name: "Weevil Custom", Class: "MUSCLE", Price: calcPrice(36.500), Brand: "BF" },
                        { Model: "clique2", Name: "Clique Wagon", Class: "MUSCLE", Price: calcPrice(37.042), Brand: "Vapid" },
                        { Model: "greenwood", Name: "Greenwood", Class: "MUSCLE", Price: calcPrice(37.583), Brand: "Bravado" },
                        { Model: "vigero2", Name: "Vigero ZX", Class: "MUSCLE", Price: calcPrice(38.125), Brand: "Declasse" },
                        { Model: "dominator7", Name: "Dominator ASP", Class: "MUSCLE", Price: calcPrice(38.667), Brand: "Vapid" },
                        { Model: "gauntlet5", Name: "Gauntlet Classic Custom", Class: "MUSCLE", Price: calcPrice(39.208), Brand: "Bravado" },
                        { Model: "impaler6", Name: "Impaler LX", Class: "MUSCLE", Price: calcPrice(19.750), Brand: "Declasse" },
                        { Model: "brigham", Name: "Brigham", Class: "MUSCLE", Price: calcPrice(40.292), Brand: "Albany" },
                        { Model: "coquette3", Name: "Coquette BlackFin", Class: "MUSCLE", Price: calcPrice(40.833), Brand: "Invetero" },
                        
                        { Model: "buffalo5", Name: "Buffalo EVX", Class: "MUSCLE", Price: calcPrice(41.917), Brand: "Bravado" },
                        { Model: "dominator9", Name: "Dominator GT", Class: "MUSCLE", Price: calcPrice(42.458), Brand: "Vapid" },
                        { Model: "vigero3", Name: "Vigero ZX Convertible", Class: "MUSCLE", Price: calcPrice(43.000), Brand: "Declasse" },
                        { Model: "buffalo4", Name: "Buffalo STX", Class: "MUSCLE", Price: calcPrice(43.000), Brand: "Bravado" },
                        { Model: "hermes", Name: "Hermes", Class: "MUSCLE", Price: calcPrice(43.000), Brand: "Albany" },
                    


    { Model: "cheburek", Name: "Cheburek", Class: "SPORT_CLASSIC", Price: calcPrice(6.500), Brand: "Rune" },
    { Model: "fagaloa", Name: "Fagaloa", Class: "SPORT_CLASSIC", Price: calcPrice(7.202), Brand: "Vulcar" },
    { Model: "tornado", Name: "Tornado", Class: "SPORT_CLASSIC", Price: calcPrice(7.905), Brand: "Declasse" },
    { Model: "nebula", Name: "Nebula", Class: "SPORT_CLASSIC", Price: calcPrice(8.607), Brand: "Vulcar" },
    { Model: "tornado2", Name: "Tornado Convertible", Class: "SPORT_CLASSIC", Price: calcPrice(9.310), Brand: "Declasse" },
    { Model: "tornado5", Name: "Tornado Custom", Class: "SPORT_CLASSIC", Price: calcPrice(10.012), Brand: "Declasse" },
    { Model: "peyote", Name: "Peyote", Class: "SPORT_CLASSIC", Price: calcPrice(10.714), Brand: "Vapid" },
    { Model: "dynasty", Name: "Dynasty", Class: "SPORT_CLASSIC", Price: calcPrice(11.417), Brand: "Weeny" },
    { Model: "michelli", Name: "Michelli GT", Class: "SPORT_CLASSIC", Price: calcPrice(12.821), Brand: "Lampadati" },
    { Model: "retinue", Name: "Retinue", Class: "SPORT_CLASSIC", Price: calcPrice(13.524), Brand: "Vapid" },
    { Model: "retinue2", Name: "Retinue MKII", Class: "SPORT_CLASSIC", Price: calcPrice(14.226), Brand: "Vapid" },
    { Model: "stinger", Name: "Stinger", Class: "SPORT_CLASSIC", Price: calcPrice(23.929), Brand: "Grotti" },
    { Model: "jb7002", Name: "JB 700W", Class: "SPORT_CLASSIC", Price: calcPrice(15.631), Brand: "Dewbauchee" },
    { Model: "peyote2", Name: "Peyote Gasser", Class: "SPORT_CLASSIC", Price: calcPrice(16.333), Brand: "Vapid" },
    { Model: "zion3", Name: "Zion Classic", Class: "SPORT_CLASSIC", Price: calcPrice(17.036), Brand: "Übermacht" },
    { Model: "peyote3", Name: "Peyote Custom", Class: "SPORT_CLASSIC", Price: calcPrice(17.738), Brand: "Vapid" },
    { Model: "btype3", Name: "Roosevelt Valor", Class: "SPORT_CLASSIC", Price: calcPrice(19.845), Brand: "Albany" },
    { Model: "savestra", Name: "Savestra", Class: "SPORT_CLASSIC", Price: calcPrice(20.548), Brand: "Annis" },
    { Model: "stingergt", Name: "Stinger GT", Class: "SPORT_CLASSIC", Price: calcPrice(25.250), Brand: "Grotti" },
    { Model: "btype", Name: "Roosevelt", Class: "SPORT_CLASSIC", Price: calcPrice(21.952), Brand: "Albany" },
    { Model: "z190", Name: "190Z", Class: "SPORT_CLASSIC", Price: calcPrice(22.655), Brand: "Karin" },
    { Model: "torero", Name: "Torero", Class: "SPORT_CLASSIC", Price: calcPrice(24.060), Brand: "Pegassi" },
    { Model: "btype2", Name: "Franken Stange", Class: "SPORT_CLASSIC", Price: calcPrice(24.762), Brand: "Albany" },
    { Model: "rapidgt3", Name: "Rapid GT Classic", Class: "SPORT_CLASSIC", Price: calcPrice(25.464), Brand: "Dewbauchee" },
    { Model: "pigalle", Name: "Pigalle", Class: "SPORT_CLASSIC", Price: calcPrice(26.167), Brand: "Lampadati" },
    { Model: "casco", Name: "Casco", Class: "SPORT_CLASSIC", Price: calcPrice(26.869), Brand: "Lampadati" },
    { Model: "driftnebula", Name: "Nebula Turbo", Class: "SPORT_CLASSIC", Price: calcPrice(27.571), Brand: "Vulcar" },
    { Model: "monroe", Name: "Monroe", Class: "SPORT_CLASSIC", Price: calcPrice(28.274), Brand: "Pegassi" },
    { Model: "feltzer3", Name: "Stirling GT", Class: "SPORT_CLASSIC", Price: calcPrice(28.976), Brand: "Benefactor" },
    { Model: "gt500", Name: "GT500", Class: "SPORT_CLASSIC", Price: calcPrice(29.679), Brand: "Grotti" },
    { Model: "mamba", Name: "Mamba", Class: "SPORT_CLASSIC", Price: calcPrice(30.381), Brand: "Declasse" },
    { Model: "coquette2", Name: "Coquette Classic", Class: "SPORT_CLASSIC", Price: calcPrice(31.083), Brand: "Invetero" },
    { Model: "turismo2", Name: "Turismo Classic", Class: "SPORT_CLASSIC", Price: calcPrice(31.786), Brand: "Grotti" },
    { Model: "envisage", Name: "Envisage", Class: "SPORT_CLASSIC", Price: calcPrice(32.488), Brand: "Bollokan" },
    { Model: "viseris", Name: "Viseris", Class: "SPORT_CLASSIC", Price: calcPrice(33.190), Brand: "Lampadati" },
    { Model: "swinger", Name: "Swinger", Class: "SPORT_CLASSIC", Price: calcPrice(33.893), Brand: "Ocelot" },
    { Model: "infernus2", Name: "Infernus Classic", Class: "SPORT_CLASSIC", Price: calcPrice(35.298), Brand: "Pegassi" },
    { Model: "ztype", Name: "Z-Type", Class: "SPORT_CLASSIC", Price: calcPrice(36.000), Brand: "Truffade" },


    { Model: "issi8", Name: "Issi Rally", Class: "SPORT", Price: calcPrice(24.000 ), Brand: "Weeny" },
    { Model: "buffalo", Name: "Buffalo", Class: "SPORT", Price: calcPrice(24.427 ), Brand: "Bravado" },
    { Model: "schafter4", Name: "Schafter LWB", Class: "SPORT", Price: calcPrice(14.854 ), Brand: "Benefactor" },
    { Model: "penumbra", Name: "Penumbra", Class: "SPORT", Price: calcPrice(25.281 ), Brand: "Maibatsu" },
    { Model: "buffalo2", Name: "Buffalo S", Class: "SPORT", Price: calcPrice(25.708 ), Brand: "Bravado" },
    { Model: "penumbra2", Name: "Penumbra FF", Class: "SPORT", Price: calcPrice(26.135 ), Brand: "Maibatsu" },
    { Model: "schafter3", Name: "Schafter V12", Class: "SPORT", Price: calcPrice(26.562 ), Brand: "Benefactor" },
    { Model: "bestiagts", Name: "Bestia GTS", Class: "SPORT", Price: calcPrice(26.990 ), Brand: "Grotti" },
    { Model: "zr350", Name: "ZR350", Class: "SPORT", Price: calcPrice(27.417 ), Brand: "Annis" },
    { Model: "calico", Name: "Calico GTF", Class: "SPORT", Price: calcPrice(27.844 ), Brand: "Karin" },
    { Model: "futo2", Name: "Futo GTX", Class: "SPORT", Price: calcPrice(28.271 ), Brand: "Karin" },
    { Model: "streiter", Name: "Streiter", Class: "SPORT", Price: calcPrice(28.698 ), Brand: "Benefactor" },
    { Model: "schwarzer", Name: "Schwartzer", Class: "SPORT", Price: calcPrice(29.125 ), Brand: "Benefactor" },
    { Model: "flashgt", Name: "Flash GT", Class: "SPORT", Price: calcPrice(29.552 ), Brand: "Vapid" },
    { Model: "remus", Name: "Remus", Class: "SPORT", Price: calcPrice(29.979 ), Brand: "Annis" },
    { Model: "sultan", Name: "Sultan", Class: "SPORT", Price: calcPrice(30.406 ), Brand: "Karin" },
    { Model: "alpha", Name: "Alpha", Class: "SPORT", Price: calcPrice(30.833 ), Brand: "Albany" },
    { Model: "komoda", Name: "Komoda", Class: "SPORT", Price: calcPrice(31.260 ), Brand: "Lampadati" },
    { Model: "panthere", Name: "Panthere", Class: "SPORT", Price: calcPrice(31.687 ), Brand: "Toundra" },
    { Model: "sultan2", Name: "Sultan Custom", Class: "SPORT", Price: calcPrice(32.115 ), Brand: "Karin" },
    { Model: "r300", Name: "300R", Class: "SPORT", Price: calcPrice(32.542 ), Brand: "Annis" },
    { Model: "banshee", Name: "Banshee", Class: "SPORT", Price: calcPrice(32.969 ), Brand: "Bravado" },
    { Model: "sultan3", Name: "Sultan Classic Custom", Class: "SPORT", Price: calcPrice(33.396 ), Brand: "Karin" },
    { Model: "paragon", Name: "Paragon", Class: "SPORT", Price: calcPrice(33.823 ), Brand: "Enus" },
    { Model: "rt3000", Name: "RT3000", Class: "SPORT", Price: calcPrice(34.250 ), Brand: "Dinka" },
    { Model: "tropos", Name: "Tropos Rallye", Class: "SPORT", Price: calcPrice(34.677 ), Brand: "Lampadati" },
    { Model: "kuruma", Name: "Kuruma", Class: "SPORT", Price: calcPrice(35.104 ), Brand: "Karin" },
    { Model: "sultanrs", Name: "Sultan RS", Class: "SPORT", Price: calcPrice(35.958 ), Brand: "Karin" },
    { Model: "furoregt", Name: "Furore GT", Class: "SPORT", Price: calcPrice(36.385 ), Brand: "Lampadati" },
    { Model: "drafter", Name: "8F Drafter", Class: "SPORT", Price: calcPrice(36.812 ), Brand: "Obey" },
    { Model: "euros", Name: "Euros", Class: "SPORT", Price: calcPrice(37.240 ), Brand: "Annis" },
    { Model: "everon2", Name: "Everon Hotring", Class: "SPORT", Price: calcPrice(37.667 ), Brand: "Karin" },
    { Model: "jugular", Name: "Jugular", Class: "SPORT", Price: calcPrice(38.094 ), Brand: "Ocelot" },
    { Model: "massacro2", Name: "Massacro Racecar", Class: "SPORT", Price: calcPrice(38.521 ), Brand: "Dewbauchee" },
    { Model: "surano", Name: "Surano", Class: "SPORT", Price: calcPrice(38.948 ), Brand: "Benefactor" },
    { Model: "vstr", Name: "V-STR", Class: "SPORT", Price: calcPrice(39.375 ), Brand: "Albany" },
    { Model: "vectre", Name: "Vectre", Class: "SPORT", Price: calcPrice(39.802 ), Brand: "Emperor" },
    { Model: "jester3", Name: "Jester Classic", Class: "SPORT", Price: calcPrice(40.229 ), Brand: "Dinka" },
    { Model: "sugoi", Name: "Sugoi", Class: "SPORT", Price: calcPrice(40.656 ), Brand: "Dinka" },
    { Model: "rapidgt", Name: "Rapid GT", Class: "SPORT", Price: calcPrice(41.083 ), Brand: "Dewbauchee" },
    { Model: "corsita", Name: "Corsita", Class: "SPORT", Price: calcPrice(41.510 ), Brand: "Lampadati" },
    { Model: "khamelion", Name: "Khamelion", Class: "SPORT", Price: calcPrice(41.937 ), Brand: "Hijak" },
    { Model: "omnis", Name: "Omnis", Class: "SPORT", Price: calcPrice(42.365 ), Brand: "Wow" },
    { Model: "pariah", Name: "Pariah", Class: "SPORT", Price: calcPrice(42.792 ), Brand: "Ocelot" },
    { Model: "raptor", Name: "Raptor", Class: "SPORT", Price: calcPrice(43.219 ), Brand: "BF" },
    { Model: "verlierer2", Name: "Verlierer", Class: "SPORT", Price: calcPrice(43.646 ), Brand: "Bravado" },
    { Model: "rapidgt2", Name: "Rapid GT Convertible", Class: "SPORT", Price: calcPrice(44.073 ), Brand: "Dewbauchee" },
    { Model: "ninef", Name: "9F", Class: "SPORT", Price: calcPrice(44.500 ), Brand: "Obey" },
    { Model: "revolter", Name: "Revolter", Class: "SPORT", Price: calcPrice(44.927 ), Brand: "Übermacht" },
    { Model: "feltzer2", Name: "Feltzer", Class: "SPORT", Price: calcPrice(45.354 ), Brand: "Benefactor" },
    { Model: "ninef2", Name: "9F Cabrio", Class: "SPORT", Price: calcPrice(45.781 ), Brand: "Obey" },
    { Model: "comet4", Name: "Comet Safari", Class: "SPORT", Price: calcPrice(46.208 ), Brand: "Pfister" },
    { Model: "massacro", Name: "Massacro", Class: "SPORT", Price: calcPrice(46.635 ), Brand: "Dewbauchee" },
    { Model: "imorgon", Name: "Imorgon", Class: "SPORT", Price: calcPrice(47.062 ), Brand: "Överflöd" },
    { Model: "sm722", Name: "SM722", Class: "SPORT", Price: calcPrice(47.490 ), Brand: "Benefactor" },
    { Model: "comet2", Name: "Comet", Class: "SPORT", Price: calcPrice(47.917 ), Brand: "Pfister" },
    { Model: "ruston", Name: "Ruston", Class: "SPORT", Price: calcPrice(48.344 ), Brand: "Hijak" },
    { Model: "jester", Name: "Jester", Class: "SPORT", Price: calcPrice(48.771 ), Brand: "Dinka" },
    { Model: "gb200", Name: "GB 200", Class: "SPORT", Price: calcPrice(49.198 ), Brand: "Vapid" },
    { Model: "sentinel4", Name: "Sentinel Classic Widebody", Class: "SPORT", Price: calcPrice(49.625 ), Brand: "Übermacht" },
    { Model: "seven70", Name: "Seven-70", Class: "SPORT", Price: calcPrice(50.052 ), Brand: "Dewbauchee" },
    { Model: "coquette", Name: "Coquette", Class: "SPORT", Price: calcPrice(50.479 ), Brand: "Invetero" },
    { Model: "elegy", Name: "Elegy Retro Custom", Class: "SPORT", Price: calcPrice(50.906 ), Brand: "Annis" },
    { Model: "driftsentinel", Name: "Drift Sentinel Classic", Class: "SPORT", Price: calcPrice(51.333 ), Brand: "Ubermacht" },
    { Model: "elegy2", Name: "Elegy RH8", Class: "SPORT", Price: calcPrice(51.760 ), Brand: "Annis" },
    { Model: "lynx", Name: "Lynx", Class: "SPORT", Price: calcPrice(52.187 ), Brand: "Ocelot" },
    { Model: "carbonizzare", Name: "Carbonizzare", Class: "SPORT", Price: calcPrice(52.615 ), Brand: "Grotti" },
    { Model: "comet5", Name: "Comet SR", Class: "SPORT", Price: calcPrice(53.042 ), Brand: "Pfister" },
    { Model: "cypher", Name: "Cypher", Class: "SPORT", Price: calcPrice(53.469 ), Brand: "Übermacht" },
    { Model: "driftcypher", Name: "Drift Cypher", Class: "SPORT", Price: calcPrice(53.896 ), Brand: "Ubermacht" },
    { Model: "schlagen", Name: "Schlagen GT", Class: "SPORT", Price: calcPrice(54.323 ), Brand: "Benefactor" },
    { Model: "specter", Name: "Specter", Class: "SPORT", Price: calcPrice(54.750 ), Brand: "Dewbauchee" },
    { Model: "comet3", Name: "Comet Retro Custom", Class: "SPORT", Price: calcPrice(55.177 ), Brand: "Pfister" },
    { Model: "eurosX32", Name: "Euros X32", Class: "SPORT", Price: calcPrice(55.604 ), Brand: "Annis" },
    { Model: "niobe", Name: "Niobe", Class: "SPORT", Price: calcPrice(56.031 ), Brand: "Ubermacht" },
    { Model: "gauntlet6", Name: "Hotring Hellfire", Class: "SPORT", Price: calcPrice(56.458 ), Brand: "Bravado" },
    { Model: "tenf", Name: "10F", Class: "SPORT", Price: calcPrice(56.885 ), Brand: "Obey" },
    { Model: "omnisegt", Name: "Omnis e-GT", Class: "SPORT", Price: calcPrice(57.312 ), Brand: "Obey" },
    { Model: "cheetah2", Name: "Cheetah Classic", Class: "SPORT", Price: calcPrice(57.740 ), Brand: "Grotti" },
    { Model: "coureur", Name: "La Coureuse", Class: "SPORT", Price: calcPrice(58.167 ), Brand: "Penaud" },
    { Model: "locust", Name: "Locust", Class: "SPORT", Price: calcPrice(58.594 ), Brand: "Ocelot" },
    { Model: "growler", Name: "Growler", Class: "SPORT", Price: calcPrice(59.021 ), Brand: "Pfister" },
    { Model: "jester2", Name: "Jester Racecar", Class: "SPORT", Price: calcPrice(59.448 ), Brand: "Dinka" },
    { Model: "tenf2", Name: "10F Widebody", Class: "SPORT", Price: calcPrice(59.875 ), Brand: "Obey" },
    { Model: "coquette5", Name: "Coquette D1", Class: "SPORT", Price: calcPrice(60.302 ), Brand: "Invetero" },
    { Model: "coquette4", Name: "Coquette D10", Class: "SPORT", Price: calcPrice(60.729 ), Brand: "Invetero" },
    { Model: "neon", Name: "Neon", Class: "SPORT", Price: calcPrice(61.156 ), Brand: "Pfister" },
    { Model: "paragon3", Name: "Paragon S", Class: "SPORT", Price: calcPrice(61.583 ), Brand: "Enus" },
    { Model: "comet6", Name: "Comet S2", Class: "SPORT", Price: calcPrice(62.010 ), Brand: "Pfister" },
    { Model: "neo", Name: "Neo", Class: "SPORT", Price: calcPrice(62.437 ), Brand: "Vysser" },
    { Model: "stingertt", Name: "Itali GTO Stinger TT", Class: "SPORT", Price: calcPrice(62.865 ), Brand: "Maibatsu" },
    { Model: "jester4", Name: "Jester RR", Class: "SPORT", Price: calcPrice(63.292 ), Brand: "Dinka" },
    { Model: "pipistrello", Name: "Pipistrello", Class: "SPORT", Price: calcPrice(63.719 ), Brand: "Overflod" },
    { Model: "vorschlaghammer", Name: "Vorschlaghammer", Class: "SPORT", Price: calcPrice(64.146 ), Brand: "Pfister" },
    { Model: "driftvorschlag", Name: "Vorschlaghammer Drift", Class: "SPORT", Price: calcPrice(64.573 ), Brand: "Pfister" },
    { Model: "italigto", Name: "Itali GTO", Class: "SPORT", Price: calcPrice(65.000 ), Brand: "Progen" },
    { Model: "italirsx", Name: "Itali RSX", Class: "SPORT", Price: calcPrice(65.000 ), Brand: "Progen" },
    { Model: "visione", Name: "Visione", Class: "SPORT", Price: calcPrice(65.000 ), Brand: "Grotti" },
    { Model: "comet7", Name: "Comet", Class: "SPORT", Price: calcPrice(38.946 ), Brand: "S2 Cabrio" },


    { Model: "virtue", Name: "Virtue", Class: "SUPER", Price: calcPrice(25.000 * 1.45), Brand: "Ocelot" },
    { Model: "sc1", Name: "SC1", Class: "SUPER", Price: calcPrice(25.700 * 1.45), Brand: "Übermacht" },
    { Model: "reaper", Name: "Reaper", Class: "SUPER", Price: calcPrice(26.400 * 1.45), Brand: "Pegassi" },
    { Model: "vacca", Name: "Vacca", Class: "SUPER", Price: calcPrice(27.100 * 1.45), Brand: "Pegassi" },
    { Model: "gp1", Name: "GP1", Class: "SUPER", Price: calcPrice(27.800 * 1.45), Brand: "Progen" },
    { Model: "banshee2", Name: "Banshee 900R", Class: "SUPER", Price: calcPrice(28.500 * 1.45), Brand: "Bravado" },
    { Model: "bullet", Name: "Bullet", Class: "SUPER", Price: calcPrice(29.200 * 1.45), Brand: "Vapid" },
    { Model: "tempesta", Name: "Tempesta", Class: "SUPER", Price: calcPrice(29.900 * 1.45), Brand: "Pegassi" },
    { Model: "voltic", Name: "Voltic", Class: "SUPER", Price: calcPrice(30.600 * 1.45), Brand: "Coil" },
    { Model: "fmj", Name: "FMJ", Class: "SUPER", Price: calcPrice(31.300 * 1.45), Brand: "Vapid" },
    { Model: "penetrator", Name: "Penetrator", Class: "SUPER", Price: calcPrice(32.000 * 1.45), Brand: "Ocelot" },
    { Model: "turismor", Name: "Turismo R", Class: "SUPER", Price: calcPrice(32.700 * 1.45), Brand: "Grotti" },
    { Model: "lm87", Name: "LM87", Class: "SUPER", Price: calcPrice(33.400 * 1.45), Brand: "Benefactor" },
    { Model: "entity2", Name: "Entity XXR", Class: "SUPER", Price: calcPrice(34.100 * 1.45), Brand: "Överflöd" },
    { Model: "italigtb", Name: "Itali GTB", Class: "SUPER", Price: calcPrice(34.800 * 1.45), Brand: "Progen" },
    { Model: "entityxf", Name: "Entity XF", Class: "SUPER", Price: calcPrice(35.500 * 1.45), Brand: "Överflöd" },
    { Model: "thrax", Name: "Thrax", Class: "SUPER", Price: calcPrice(36.200 * 1.45), Brand: "Truffade" },
    { Model: "xa21", Name: "XA-21", Class: "SUPER", Price: calcPrice(36.900 * 1.45), Brand: "Ocelot" },
    { Model: "entity3", Name: "Entity MT", Class: "SUPER", Price: calcPrice(37.600 * 1.45), Brand: "Overflod" },
    { Model: "nero", Name: "Nero", Class: "SUPER", Price: calcPrice(38.300 * 1.45), Brand: "Truffade" },
    { Model: "s80", Name: "S80RR", Class: "SUPER", Price: calcPrice(39.000 * 1.45), Brand: "Annis" },
    { Model: "cheetah", Name: "Cheetah", Class: "SUPER", Price: calcPrice(39.700 * 1.45), Brand: "Grotti" },
    { Model: "pfister811", Name: "811", Class: "SUPER", Price: calcPrice(40.400 * 1.45), Brand: "Pfister" },
    { Model: "emerus", Name: "Emerus", Class: "SUPER", Price: calcPrice(41.100 * 1.45), Brand: "Progen" },
    { Model: "sheava", Name: "ETR1", Class: "SUPER", Price: calcPrice(41.800 * 1.45), Brand: "Emperor" },
    { Model: "osiris", Name: "Osiris", Class: "SUPER", Price: calcPrice(42.500 * 1.45), Brand: "Pegassi" },
    { Model: "tezeract", Name: "Tezeract", Class: "SUPER", Price: calcPrice(43.200 * 1.45), Brand: "Pegassi" },
    { Model: "krieger", Name: "Krieger", Class: "SUPER", Price: calcPrice(43.900 * 1.45), Brand: "Benefactor" },
    { Model: "autarch", Name: "Autarch", Class: "SUPER", Price: calcPrice(44.600 * 1.45), Brand: "Överflöd" },
    { Model: "furia", Name: "Furia", Class: "SUPER", Price: calcPrice(45.300 * 1.45), Brand: "Grotti" },
    { Model: "tyrus", Name: "Tyrus", Class: "SUPER", Price: calcPrice(46.000 * 1.45), Brand: "Progen" },
    { Model: "deveste", Name: "Deveste", Class: "SUPER", Price: calcPrice(46.700 * 1.45), Brand: "Principe" },
    { Model: "infernus", Name: "Infernus", Class: "SUPER", Price: calcPrice(47.400 * 1.45), Brand: "Pegassi" },
    { Model: "prototipo", Name: "X80 Proto", Class: "SUPER", Price: calcPrice(48.100 * 1.45), Brand: "Grotti" },
    { Model: "tigon", Name: "Tigon", Class: "SUPER", Price: calcPrice(48.800 * 1.45), Brand: "Lampadati" },
    { Model: "torero2", Name: "Torero XO", Class: "SUPER", Price: calcPrice(49.500 * 1.45), Brand: "Pegassi" },
    { Model: "italigtb2", Name: "Itali GTB Custom", Class: "SUPER", Price: calcPrice(50.200 * 1.45), Brand: "Progen" },
    { Model: "nero2", Name: "Nero Custom", Class: "SUPER", Price: calcPrice(50.900 * 1.45), Brand: "Truffade" },
    { Model: "le7b", Name: "RE-7B", Class: "SUPER", Price: calcPrice(51.600 * 1.45), Brand: "Annis" },
    { Model: "zorrusso", Name: "Zorrusso", Class: "SUPER", Price: calcPrice(52.300 * 1.45), Brand: "Pegassi" },
    { Model: "adder", Name: "Adder", Class: "SUPER", Price: calcPrice(53.000 * 1.45), Brand: "Truffade" },
    { Model: "turismo3", Name: "Turismo Omaggio", Class: "SUPER", Price: calcPrice(53.700 * 1.45), Brand: "Grotti" },
    { Model: "cyclone", Name: "Cyclone", Class: "SUPER", Price: calcPrice(54.400 * 1.45), Brand: "Coil" },
    { Model: "zentorno", Name: "Zentorno", Class: "SUPER", Price: calcPrice(55.100 * 1.45), Brand: "Pegassi" },
    { Model: "ignus", Name: "Ignus", Class: "SUPER", Price: calcPrice(55.800 * 1.45), Brand: "Pegassi" },
    { Model: "zeno", Name: "Zeno", Class: "SUPER", Price: calcPrice(56.500 * 1.45), Brand: "Överflöd" },
    { Model: "t20", Name: "T20", Class: "SUPER", Price: calcPrice(57.200 * 1.45), Brand: "Progen" },
    { Model: "vagner", Name: "Vagner", Class: "SUPER", Price: calcPrice(57.900 * 1.45), Brand: "Dewbauchee" },
    { Model: "taipan", Name: "Taipan", Class: "SUPER", Price: calcPrice(58.600 * 1.45), Brand: "Cheval" },
    { Model: "tyrant", Name: "Tyrant", Class: "SUPER", Price: calcPrice(59.300 * 1.45), Brand: "Överflöd" },
 




    { Model: "faggio2", Name: "Faggio", Class: "MOTORCYCLE", Price: calcPrice(2.000), Brand: "Pegassi" },
    { Model: "faggio", Name: "Faggio Sport", Class: "MOTORCYCLE", Price: calcPrice(2.589), Brand: "Pegassi" },
    { Model: "faggio3", Name: "Faggio Mod", Class: "MOTORCYCLE", Price: calcPrice(3.179), Brand: "Pegassi" },
    { Model: "ratbike", Name: "Rat Bike", Class: "MOTORCYCLE", Price: calcPrice(3.768), Brand: "Western" },
  
    { Model: "sanchez2", Name: "Sanchez", Class: "MOTORCYCLE", Price: calcPrice(4.946), Brand: "Maibatsu" },
    { Model: "sanchez", Name: "Sanchez Livery", Class: "MOTORCYCLE", Price: calcPrice(5.536), Brand: "Maibatsu" },
    { Model: "enduro", Name: "Enduro", Class: "MOTORCYCLE", Price: calcPrice(6.125), Brand: "Dinka" },

    { Model: "vader", Name: "Vader", Class: "MOTORCYCLE", Price: calcPrice(23.304), Brand: "Shitzu" },
    { Model: "sovereign", Name: "Sovereign", Class: "MOTORCYCLE", Price: calcPrice(7.893), Brand: "WMC" },
    { Model: "manchez", Name: "Manchez", Class: "MOTORCYCLE", Price: calcPrice(15.482), Brand: "Maibatsu" },
    { Model: "esskey", Name: "Esskey", Class: "MOTORCYCLE", Price: calcPrice(9.071), Brand: "Pegassi" },
    { Model: "bagger", Name: "Bagger", Class: "MOTORCYCLE", Price: calcPrice(9.661), Brand: "WMC" },
    { Model: "daemon", Name: "Daemon", Class: "MOTORCYCLE", Price: calcPrice(10.250), Brand: "WMC" },
    { Model: "manchez2", Name: "Manchez Scout", Class: "MOTORCYCLE", Price: calcPrice(17.839), Brand: "Maibatsu" },
    { Model: "wolfsbane", Name: "Wolfsbane", Class: "MOTORCYCLE", Price: calcPrice(11.429), Brand: "Western" },
    { Model: "manchez3", Name: "Manchez Scout Classic", Class: "MOTORCYCLE", Price: calcPrice(18.018), Brand: "Maibatsu" },
    { Model: "pcj", Name: "PCJ-600", Class: "MOTORCYCLE", Price: calcPrice(18.607), Brand: "Shitzu" },
    { Model: "hexer", Name: "Hexer", Class: "MOTORCYCLE", Price: calcPrice(13.196), Brand: "LCC" },
    { Model: "hakuchou", Name: "Hakuchou", Class: "MOTORCYCLE", Price: calcPrice(33.786), Brand: "Shitzu" },
    { Model: "bati2", Name: "Bati 801RR", Class: "MOTORCYCLE", Price: calcPrice(34.375), Brand: "Pegassi" },
    { Model: "fcr2", Name: "FCR 1000 Custom", Class: "MOTORCYCLE", Price: calcPrice(24.964), Brand: "Pegassi" },

    { Model: "fcr", Name: "FCR 1000", Class: "MOTORCYCLE", Price: calcPrice(16.357), Brand: "Pegassi" },
    { Model: "avarus", Name: "Avarus", Class: "MOTORCYCLE", Price: calcPrice(16.143), Brand: "LCC" },
    { Model: "nemesis", Name: "Nemesis", Class: "MOTORCYCLE", Price: calcPrice(16.732), Brand: "Principe" },
    { Model: "chimera", Name: "Chimera", Class: "MOTORCYCLE", Price: calcPrice(17.321), Brand: "Nagasaki" },
    { Model: "bf400", Name: "BF400", Class: "MOTORCYCLE", Price: calcPrice(27.911), Brand: "Nagasaki" },
    { Model: "carbonrs", Name: "Carbon RS", Class: "MOTORCYCLE", Price: calcPrice(26.500), Brand: "Nagasaki" },
    { Model: "thrust", Name: "Thrust", Class: "MOTORCYCLE", Price: calcPrice(19.089), Brand: "Dinka" },
    { Model: "daemon2", Name: "Daemon Custom", Class: "MOTORCYCLE", Price: calcPrice(19.679), Brand: "Western" },
    { Model: "nightblade", Name: "Nightblade", Class: "MOTORCYCLE", Price: calcPrice(20.268), Brand: "WMC" },
    { Model: "bati", Name: "Bati 801", Class: "MOTORCYCLE", Price: calcPrice(20.857), Brand: "Pegassi" },
    { Model: "reever", Name: "Reever", Class: "MOTORCYCLE", Price: calcPrice(21.446), Brand: "Western" },
    { Model: "ruffian", Name: "Ruffian", Class: "MOTORCYCLE", Price: calcPrice(22.036), Brand: "Pegassi" },
    { Model: "shinobi", Name: "Shinobi", Class: "MOTORCYCLE", Price: calcPrice(22.625), Brand: "Nagasaki" },
    { Model: "zombieb", Name: "Zombie Chopper", Class: "MOTORCYCLE", Price: calcPrice(23.214), Brand: "Western" },
    { Model: "double", Name: "Double-T", Class: "MOTORCYCLE", Price: calcPrice(23.804), Brand: "Dinka" },
    { Model: "lectro", Name: "Lectro", Class: "MOTORCYCLE", Price: calcPrice(24.393), Brand: "Principe" },
    { Model: "zombiea", Name: "Zombie Bobber", Class: "MOTORCYCLE", Price: calcPrice(24.982), Brand: "Western" },
    { Model: "cliffhanger", Name: "Cliffhanger", Class: "MOTORCYCLE", Price: calcPrice(25.571), Brand: "Western" },
    { Model: "powersurge", Name: "Powersurge", Class: "MOTORCYCLE", Price: calcPrice(26.714), Brand: "Western" },
    { Model: "defiler", Name: "Defiler", Class: "MOTORCYCLE", Price: calcPrice(27.929), Brand: "Shitzu" },
    { Model: "diablous", Name: "Diablous", Class: "MOTORCYCLE", Price: calcPrice(28.518), Brand: "Principe" },
    { Model: "vortex", Name: "Vortex", Class: "MOTORCYCLE", Price: calcPrice(29.107), Brand: "Pegassi" },
    { Model: "gargoyle", Name: "Gargoyle", Class: "MOTORCYCLE", Price: calcPrice(29.696), Brand: "Western" },
    { Model: "innovation", Name: "Innovation", Class: "MOTORCYCLE", Price: calcPrice(30.286), Brand: "LLC" },
    { Model: "sanctus", Name: "Sanctus", Class: "MOTORCYCLE", Price: calcPrice(30.875), Brand: "LCC" },
    { Model: "diablous2", Name: "Diablous Custom", Class: "MOTORCYCLE", Price: calcPrice(31.464), Brand: "Principe" },
    { Model: "hakuchou2", Name: "Hakuchou Drag", Class: "MOTORCYCLE", Price: calcPrice(32.054), Brand: "Shitzu" },
    { Model: "stryder", Name: "Stryder", Class: "MOTORCYCLE", Price: calcPrice(33.232), Brand: "Nagasaki" },
    { Model: "akuma", Name: "Akuma", Class: "MOTORCYCLE", Price: calcPrice(33.821), Brand: "Dinka" },
    { Model: "shotaro", Name: "Shotaro", Class: "MOTORCYCLE", Price: calcPrice(34.411), Brand: "Nagasaki" },








    { Model: "blazer3", Name: "Blazer Hot Rod", Class: "OFF_ROAD", Price: calcPrice(10.000), Brand: "Nagasaki" },

    { Model: "blazer", Name: "Blazer", Class: "OFF_ROAD", Price: calcPrice(11.778), Brand: "Annis" },
    { Model: "bfinjection", Name: "Bf Injection", Class: "OFF_ROAD", Price: calcPrice(12.667), Brand: "Annis" },
    { Model: "blazer4", Name: "Blazer Sport", Class: "OFF_ROAD", Price: calcPrice(13.556), Brand: "Annis" },

    { Model: "mesa", Name: "Mesa", Class: "OFF_ROAD", Price: calcPrice(15.333), Brand: "Canis" },
    { Model: "dune", Name: "Dune Buggy", Class: "OFF_ROAD", Price: calcPrice(16.222), Brand: "Annis" },
    { Model: "kalahari", Name: "Kalahari", Class: "OFF_ROAD", Price: calcPrice(9.511), Brand: "Canis" },
    { Model: "outlaw", Name: "Outlaw", Class: "OFF_ROAD", Price: calcPrice(31.000), Brand: "Nagasaki" },
    { Model: "bifta", Name: "Bifta", Class: "OFF_ROAD", Price: calcPrice(18.889), Brand: "Annis" },
    { Model: "rebel2", Name: "Rebel", Class: "OFF_ROAD", Price: calcPrice(19.778), Brand: "Vapid" },
    { Model: "verus", Name: "Verus", Class: "OFF_ROAD", Price: calcPrice(20.667), Brand: "Dinka" },
    { Model: "rancherxl", Name: "Rancher XL", Class: "OFF_ROAD", Price: calcPrice(22.444), Brand: "Declasse" },
    { Model: "sandking", Name: "Sandking XL", Class: "OFF_ROAD", Price: calcPrice(23.333), Brand: "Vapid" },
    { Model: "dubsta3", Name: "Dubsta 6x6", Class: "OFF_ROAD", Price: calcPrice(24.222), Brand: "Annis" },
    { Model: "hellion", Name: "Hellion", Class: "OFF_ROAD", Price: calcPrice(25.111), Brand: "Annis" },
    { Model: "sandking2", Name: "Sandking SWB", Class: "OFF_ROAD", Price: calcPrice(22.500), Brand: "Vapid" },
    { Model: "brawler", Name: "Brawler", Class: "OFF_ROAD", Price: calcPrice(34.778), Brand: "Annis" },
    { Model: "kamacho", Name: "Kamacho", Class: "OFF_ROAD", Price: calcPrice(36.556), Brand: "Canis" },
    { Model: "vagrant", Name: "Vagrant", Class: "OFF_ROAD", Price: calcPrice(30.444), Brand: "Maxwell" },
    { Model: "everon", Name: "Everon", Class: "OFF_ROAD", Price: calcPrice(32.222), Brand: "Karin" },
    { Model: "trophytruck", Name: "Trophy Truck", Class: "OFF_ROAD", Price: calcPrice(37.111), Brand: "Vapid" },
    { Model: "caracara2", Name: "Caracara 4x4", Class: "OFF_ROAD", Price: calcPrice(34.000), Brand: "Vapid" },
    { Model: "trophytruck2", Name: "Desert Raid", Class: "OFF_ROAD", Price: calcPrice(39.889), Brand: "Vapid" },
    { Model: "draugur", Name: "Draugur", Class: "OFF_ROAD", Price: calcPrice(48.778), Brand: "Declasse" },
    { Model: "l35", Name: "Walton L35", Class: "OFF_ROAD", Price: calcPrice(36.667), Brand: "Declasse" },
    { Model: "terminus", Name: "Terminus", Class: "OFF_ROAD", Price: calcPrice(37.556), Brand: "Canis" },
    { Model: "ratel", Name: "Ratel", Class: "OFF_ROAD", Price: calcPrice(39.333), Brand: "Vapid" },
    { Model: "riata", Name: "Riata", Class: "OFF_ROAD", Price: calcPrice(24.222), Brand: "Vapid" },
    { Model: "mesa3", Name: "Mesa Merryweather", Class: "OFF_ROAD", Price: calcPrice(23.111), Brand: "Canis" },
    { Model: "yosemite3", Name: "Yosemite Rancher", Class: "OFF_ROAD", Price: calcPrice(23.000), Brand: "Declasse" },




        { Model: "burrito3", Name: "Burrito", Class: "VAN", Price: calcPrice(7.000), Brand: "Declasse" },
        { Model: "journey", Name: "Journey", Class: "VAN", Price: calcPrice(7.563), Brand: "Zirconium" },
        { Model: "journey2", Name: "Journey II", Class: "VAN", Price: calcPrice(8.125), Brand: "Zirconium" },
        { Model: "minivan", Name: "Minivan", Class: "VAN", Price: calcPrice(8.688), Brand: "Vapid" },
        { Model: "youga", Name: "Youga", Class: "VAN", Price: calcPrice(9.250), Brand: "Bravado" },
        { Model: "paradise", Name: "Paradise", Class: "VAN", Price: calcPrice(9.813), Brand: "Bravado" },
        { Model: "surfer", Name: "Surfer", Class: "VAN", Price: calcPrice(10.938), Brand: "BF" },
        { Model: "minivan2", Name: "Minivan Custom", Class: "VAN", Price: calcPrice(11.500), Brand: "Vapid" },
        { Model: "speedo", Name: "Speedo", Class: "VAN", Price: calcPrice(12.063), Brand: "Vapid" },
        { Model: "gburrito2", Name: "Burrito Custom", Class: "VAN", Price: calcPrice(12.625), Brand: "Declasse" },
        { Model: "moonbeam", Name: "Moonbeam", Class: "VAN", Price: calcPrice(13.188), Brand: "Declasse" },
        { Model: "bobcatxl", Name: "Bobcat XL Open", Class: "VAN", Price: calcPrice(13.750), Brand: "Vapid" },
        { Model: "youga2", Name: "Youga Classic", Class: "VAN", Price: calcPrice(14.313), Brand: "Bravado" },
        { Model: "moonbeam2", Name: "Moonbeam Custom", Class: "VAN", Price: calcPrice(14.875), Brand: "Declasse" },
        { Model: "speedo4", Name: "Speedo Custom", Class: "VAN", Price: calcPrice(15.438), Brand: "Vapid" },
        { Model: "surfer3", Name: "Surfer Custom", Class: "VAN", Price: calcPrice(16.000), Brand: "BF" },
        { Model: "youga3", Name: "Youga Classic 4x4", Class: "VAN", Price: calcPrice(16.563), Brand: "Bravado" },
        { Model: "bison", Name: "Bison", Class: "VAN", Price: calcPrice(17.125), Brand: "Bravado" },




       
     





  
    




    // { Model: "cutter", Name: "Cutter", Class: "industrial", Price: calcPrice(30000) , Brand: "HVY" },
    // { Model: "handler", Name: "Dock Handler", Class: "industrial", Price: calcPrice(30000) , Brand: "HVY" },
    // { Model: "bulldozer", Name: "Dozer", Class: "industrial", Price: calcPrice(30000) , Brand: "HVY" },
    // { Model: "dump", Name: "Dump Truck", Class: "industrial", Price: calcPrice(30000) , Brand: "HVY" },
    // { Model: "flatbed", Name: "Flatbed Truck", Class: "industrial", Price: calcPrice(30000) , Brand: "MTL" },
    // { Model: "guardian", Name: "Guardian", Class: "industrial", Price: calcPrice(30000) , Brand: "Vapid" },
    // { Model: "mixer", Name: "Mixer", Class: "industrial", Price: calcPrice(30000) , Brand: "HVY" },
    // { Model: "mixer2", Name: "Mixer II", Class: "industrial", Price: calcPrice(30000) , Brand: "HVY" },
    // { Model: "rubble", Name: "Rubble", Class: "industrial", Price: calcPrice(30000) , Brand: "Jobuilt" },
    // { Model: "tiptruck", Name: "Tipper", Class: "industrial", Price: calcPrice(30000) , Brand: "Brute" },
    // { Model: "tiptruck2", Name: "Tipper II", Class: "industrial", Price: calcPrice(30000) , Brand: "Brute" },
    // { Model: "sadler", Name: "Sadler", Class: "utility", Price: calcPrice(20000) , Brand: "Vapid" },
    // { Model: "airtug", Name: "Airtug", Class: "utility", Price: calcPrice(30000) , Brand: "HVY" },
    // { Model: "caddy3", Name: "Caddy (Bunker)", Class: "utility", Price: calcPrice(30000) , Brand: "Nagasaki" },
    // { Model: "caddy2", Name: "Caddy (Civilian)", Class: "utility", Price: calcPrice(30000) , Brand: "Nagasaki" },
    // { Model: "caddy3", Name: "Caddy (Golf)", Class: "utility", Price: calcPrice(30000) , Brand: "Nagasaki" },
    // { Model: "docktug", Name: "Docktug", Class: "utility", Price: calcPrice(30000) , Brand: "HVY" },
    // { Model: "tractor2", Name: "Fieldmaster", Class: "utility", Price: calcPrice(30000) , Brand: "Stanley" },
    // { Model: "tractor3", Name: "Fieldmaster", Class: "utility", Price: calcPrice(30000) , Brand: "Stanley" },
    // { Model: "forklift", Name: "Forklift", Class: "utility", Price: calcPrice(30000) , Brand: "HVY" },
    // { Model: "mower", Name: "Lawn Mower", Class: "utility", Price: calcPrice(30000) , Brand: "Jacksheepe" },
    // { Model: "ripley", Name: "Ripley", Class: "utility", Price: calcPrice(30000) , Brand: "HVY" },
    // { Model: "scrap", Name: "Scrap Truck", Class: "utility", Price: calcPrice(30000) , Brand: "Vapid" },
    // { Model: "towtruck", Name: "Tow Truck (Large)", Class: "utility", Price: calcPrice(30000) , Brand: "Vapid" },
    // { Model: "towtruck2", Name: "Tow Truck (Small)", Class: "utility", Price: calcPrice(30000) , Brand: "Vapid" },
    // { Model: "tractor", Name: "Tractor", Class: "utility", Price: calcPrice(30000) , Brand: "Stanley" },
    // { Model: "trailers5", Name: "Trailer (Christmas)", Class: "utility", Price: calcPrice(30000) , Brand: "Unknown" },
    // { Model: "tvtrailer2", Name: "Trailer (TV)", Class: "utility", Price: calcPrice(30000) , Brand: "Unknown" },
    // { Model: "utillitruck", Name: "Utility Truck (Cherry Picker)", Class: "utility", Price: calcPrice(30000) , Brand: "Brute" },
    // { Model: "utillitruck3", Name: "Utility Truck (Contender)", Class: "utility", Price: calcPrice(30000) , Brand: "Vapid" },
    // { Model: "utillitruck2", Name: "Utility Truck (Van)", Class: "utility", Price: calcPrice(30000) , Brand: "Brute" },
    // { Model: "slamtruck", Name: "Slam Truck", Class: "utility", Price: calcPrice(100000) , Brand: "Vapid" },
    // { Model: "bmx", Name: "BMX", Class: "cycles", Price: calcPrice(160) , Brand: "Bike" },
    // { Model: "fixter", Name: "Fixter", Class: "cycles", Price: calcPrice(225) , Brand: "Bike" },
    // { Model: "scorcher", Name: "Scorcher", Class: "cycles", Price: calcPrice(280) , Brand: "Bike" },
    // { Model: "tribike", Name: "Whippet Race Bike", Class: "cycles", Price: calcPrice(500) , Brand: "Bike" },
    // { Model: "cruiser", Name: "Cruiser", Class: "cycles", Price: calcPrice(510) , Brand: "Bike" },
    // { Model: "tribike3", Name: "Tri-Cycles Race Bike", Class: "cycles", Price: calcPrice(520) , Brand: "Bike" },
    // { Model: "tribike2", Name: "Endurex Race Bike", Class: "cycles", Price: calcPrice(700) , Brand: "Bike" },
    // { Model: "inductor", Name: "Inductor", Class: "cycles", Price: calcPrice(5000) , Brand: "Coil" },
    // { Model: "inductor2", Name: "Junk Energy Inductor", Class: "cycles", Price: calcPrice(5000) , Brand: "Coil" },
    // { Model: "avisa", Name: "Avisa", Class: "boats", Price: calcPrice(40000) , Brand: "Kraken Subs" },
    // { Model: "dinghy3", Name: "Dinghy (Heist)", Class: "boats", Price: calcPrice(40000) , Brand: "Nagasaki" },
    // { Model: "dinghy", Name: "Dinghy 2-Seater", Class: "boats", Price: calcPrice(40000) , Brand: "Nagasaki" },
    // { Model: "dinghy2", Name: "Dinghy 4-Seater", Class: "boats", Price: calcPrice(40000) , Brand: "Nagasaki" },
    // { Model: "dinghy4", Name: "Dinghy Yacht", Class: "boats", Price: calcPrice(40000) , Brand: "Nagasaki" },
    // { Model: "jetmax", Name: "Jetmax", Class: "boats", Price: calcPrice(40000) , Brand: "Shitzu" },
    // { Model: "submersible2", Name: "Kraken", Class: "boats", Price: calcPrice(40000) , Brand: "Kraken Subs" },
    // { Model: "patrolboat", Name: "Kurtz 31 Patrol Boat", Class: "boats", Price: calcPrice(40000) , Brand: "Unknown" },
    // { Model: "longfin", Name: "Longfin", Class: "boats", Price: calcPrice(40000) , Brand: "Shitzu" },
    // { Model: "marquis", Name: "Marquis", Class: "boats", Price: calcPrice(40000) , Brand: "Dinka" },
    // { Model: "seashark", Name: "Seashark", Class: "boats", Price: calcPrice(40000) , Brand: "Speedophile" },
    // { Model: "seashark3", Name: "Seashark Yacht", Class: "boats", Price: calcPrice(40000) , Brand: "Speedophile" },
    // { Model: "speeder", Name: "Speeder", Class: "boats", Price: calcPrice(40000) , Brand: "Pegassi" },
    // { Model: "speeder2", Name: "Speeder Yacht", Class: "boats", Price: calcPrice(40000) , Brand: "Pegassi" },
    // { Model: "squalo", Name: "Squalo", Class: "boats", Price: calcPrice(40000) , Brand: "Shitzu" },
    // { Model: "submersible", Name: "Submersible", Class: "boats", Price: calcPrice(40000) , Brand: "Kraken Subs" },
    // { Model: "suntrap", Name: "Suntrap", Class: "boats", Price: calcPrice(40000) , Brand: "Shitzu" },
    // { Model: "toro", Name: "Toro", Class: "boats", Price: calcPrice(40000) , Brand: "Lampadati" },
    // { Model: "toro2", Name: "Toro Yacht", Class: "boats", Price: calcPrice(40000) , Brand: "Lampadati" },
    // { Model: "tropic", Name: "Tropic", Class: "boats", Price: calcPrice(40000) , Brand: "Shitzu" },
    // { Model: "tropic2", Name: "Tropic Yacht", Class: "boats", Price: calcPrice(40000) , Brand: "Shitzu" },
    // { Model: "tug", Name: "Tug", Class: "boats", Price: calcPrice(40000) , Brand: "Buckingham" },
    // { Model: "akula", Name: "Akula", Class: "helicopters", Price: calcPrice(52000) , Brand: "Unknown" },
    // { Model: "annihilator", Name: "Annihilator", Class: "helicopters", Price: calcPrice(52000) , Brand: "Western Company" },
    // { Model: "annihilator2", Name: "Annihilator Stealth", Class: "helicopters", Price: calcPrice(52000) , Brand: "Western Company" },
    // { Model: "buzzard2", Name: "Buzzard", Class: "helicopters", Price: calcPrice(52000) , Brand: "Nagasaki" },
    // { Model: "buzzard", Name: "Buzzard Attack Chopper", Class: "helicopters", Price: calcPrice(52000) , Brand: "Nagasaki" },
    // { Model: "cargobob", Name: "Cargobob", Class: "helicopters", Price: calcPrice(52000) , Brand: "Western Company" },
    // { Model: "cargobob3", Name: "Cargobob", Class: "helicopters", Price: calcPrice(52000) , Brand: "Western Company" },
    // { Model: "cargobob2", Name: "Cargobob Jetsam", Class: "helicopters", Price: calcPrice(52000) , Brand: "Western Company" },
    // { Model: "hunter", Name: "FH-1 Hunter", Class: "helicopters", Price: calcPrice(52000) , Brand: "Unknown" },
    // { Model: "frogger", Name: "Frogger", Class: "helicopters", Price: calcPrice(52000) , Brand: "Maibatsu" },
    // { Model: "frogger2", Name: "Frogger", Class: "helicopters", Price: calcPrice(52000) , Brand: "Maibatsu" },
    // { Model: "havok", Name: "Havok", Class: "helicopters", Price: calcPrice(52000) , Brand: "Nagasaki" },
    // { Model: "maverick", Name: "Maverick", Class: "helicopters", Price: calcPrice(52000) , Brand: "Buckingham" },
    // { Model: "savage", Name: "Savage", Class: "helicopters", Price: calcPrice(52000) , Brand: "Unknown" },
    // { Model: "seasparrow", Name: "Sea Sparrow", Class: "helicopters", Price: calcPrice(52000) , Brand: "Unknown" },
    // { Model: "skylift", Name: "Skylift", Class: "helicopters", Price: calcPrice(52000) , Brand: "HVY" },
    // { Model: "seasparrow2", Name: "Sparrow", Class: "helicopters", Price: calcPrice(52000) , Brand: "Unknown" },
    // { Model: "seasparrow3", Name: "Sparrow (Prop)", Class: "helicopters", Price: calcPrice(52000) , Brand: "Unknown" },
    // { Model: "SUPERvolito", Name: "SUPERVolito", Class: "helicopters", Price: calcPrice(52000) , Brand: "Buckingham" },
    // { Model: "SUPERvolito2", Name: "SUPERVolito Carbon", Class: "helicopters", Price: calcPrice(52000) , Brand: "Buckingham" },
    // { Model: "swift", Name: "Swift", Class: "helicopters", Price: calcPrice(52000) , Brand: "Buckingham" },
    // { Model: "swift2", Name: "Swift Deluxe", Class: "helicopters", Price: calcPrice(52000) , Brand: "Buckingham" },
    // { Model: "valkyrie", Name: "Valkyrie", Class: "helicopters", Price: calcPrice(52000) , Brand: "Buckingham" },
    // { Model: "volatus", Name: "Volatus", Class: "helicopters", Price: calcPrice(52000) , Brand: "Buckingham" },
    // { Model: "conada2", Name: "Weaponized Conada", Class: "helicopters", Price: calcPrice(52000) , Brand: "Buckingham" },
    // { Model: "conada", Name: "Conada", Class: "helicopters", Price: calcPrice(115000) , Brand: "Buckingham" },
    // { Model: "alphaz1", Name: "Alpha-Z1", Class: "planes", Price: calcPrice(45000) , Brand: "Buckingham" },
    // { Model: "blimp", Name: "Atomic Blimp", Class: "planes", Price: calcPrice(45000) , Brand: "Unknown" },
    // { Model: "avenger", Name: "Avenger", Class: "planes", Price: calcPrice(45000) , Brand: "Mammoth" },
    // { Model: "avenger2", Name: "Avenger", Class: "planes", Price: calcPrice(45000) , Brand: "Mammoth" },
    // { Model: "strikeforce", Name: "B-11 Strikeforce", Class: "planes", Price: calcPrice(45000) , Brand: "Unknown" },
    // { Model: "besra", Name: "Besra", Class: "planes", Price: calcPrice(45000) , Brand: "Western Company" },
    // { Model: "blimp3", Name: "Blimp", Class: "planes", Price: calcPrice(45000) , Brand: "Unknown" },
    // { Model: "cargoplane", Name: "Cargo Plane", Class: "planes", Price: calcPrice(45000) , Brand: "JoBuilt" },
    // { Model: "cuban800", Name: "Cuban 800", Class: "planes", Price: calcPrice(45000) , Brand: "Western Company" },
    // { Model: "dodo", Name: "Dodo", Class: "planes", Price: calcPrice(45000) , Brand: "Mammoth" },
    // { Model: "duster", Name: "Duster", Class: "planes", Price: calcPrice(45000) , Brand: "Western Company" },
    // { Model: "raiju", Name: "F-160 Raiju", Class: "planes", Price: calcPrice(45000) , Brand: "Mammoth" },
    // { Model: "howard", Name: "Howard NX-25", Class: "planes", Price: calcPrice(45000) , Brand: "Unknown" },
    // { Model: "hydra", Name: "Hydra", Class: "planes", Price: calcPrice(45000) , Brand: "Mammoth" },
    // { Model: "jet", Name: "Jet", Class: "planes", Price: calcPrice(45000) , Brand: "Unknown" },
    // { Model: "starling", Name: "LF-22 Starling", Class: "planes", Price: calcPrice(45000) , Brand: "Unknown" },
    // { Model: "luxor", Name: "Luxor", Class: "planes", Price: calcPrice(45000) , Brand: "Buckingham" },
    // { Model: "luxor2", Name: "Luxor Deluxe", Class: "planes", Price: calcPrice(45000) , Brand: "Buckingham" },
    // { Model: "stunt", Name: "Mallard", Class: "planes", Price: calcPrice(45000) , Brand: "Western Company" },
    // { Model: "mammatus", Name: "Mammatus", Class: "planes", Price: calcPrice(45000) , Brand: "JoBuilt" },
    // { Model: "miljet", Name: "Miljet", Class: "planes", Price: calcPrice(45000) , Brand: "Buckingham" },
    // { Model: "mogul", Name: "Mogul", Class: "planes", Price: calcPrice(45000) , Brand: "Mammoth" },
    // { Model: "nimbus", Name: "Nimbus", Class: "planes", Price: calcPrice(45000) , Brand: "Buckingham" },
    // { Model: "nokota", Name: "P-45 Nokota", Class: "planes", Price: calcPrice(45000) , Brand: "Unknown" },
    // { Model: "lazer", Name: "P-996 Lazer", Class: "planes", Price: calcPrice(45000) , Brand: "JoBuilt" },
    // { Model: "pyro", Name: "Pyro", Class: "planes", Price: calcPrice(45000) , Brand: "Buckingham" },
    // { Model: "bombushka", Name: "RM-10 Bombushka", Class: "planes", Price: calcPrice(45000) , Brand: "Unknown" },
    // { Model: "alkonost", Name: "RO-86 Alkonost", Class: "planes", Price: calcPrice(45000) , Brand: "Unknown" },
    // { Model: "rogue", Name: "Rogue", Class: "planes", Price: calcPrice(45000) , Brand: "Western Company" },
    // { Model: "seabreeze", Name: "Seabreeze", Class: "planes", Price: calcPrice(45000) , Brand: "Western Company" },
    // { Model: "shamal", Name: "Shamal", Class: "planes", Price: calcPrice(45000) , Brand: "Buckingham" },
    // { Model: "streamer216", Name: "Streamer216", Class: "planes", Price: calcPrice(45000) , Brand: "Mammoth" },
    // { Model: "titan", Name: "Titan", Class: "planes", Price: calcPrice(45000) , Brand: "Unknown" },
    // { Model: "tula", Name: "Tula", Class: "planes", Price: calcPrice(45000) , Brand: "Mammoth" },
    // { Model: "microlight", Name: "Ultralight", Class: "planes", Price: calcPrice(45000) , Brand: "Unknown" },
    // { Model: "molotok", Name: "V-65 Molotok", Class: "planes", Price: calcPrice(45000) , Brand: "Unknown" },
    // { Model: "velum", Name: "Velum", Class: "planes", Price: calcPrice(45000) , Brand: "JoBuilt" },
    // { Model: "velum2", Name: "Velum 5-seater", Class: "planes", Price: calcPrice(45000) , Brand: "JoBuilt" },
    // { Model: "vestra", Name: "Vestra", Class: "planes", Price: calcPrice(45000) , Brand: "Buckingham" },
    // { Model: "volatol", Name: "Volatol", Class: "planes", Price: calcPrice(45000) , Brand: "Unknown" },
    // { Model: "blimp2", Name: "Xero Blimp", Class: "planes", Price: calcPrice(45000) , Brand: "Unknown" },
    // { Model: "airbus", Name: "Airport Bus", Class: "service", Price: calcPrice(100000) , Brand: "Brute" },
    // { Model: "brickade", Name: "Brickade", Class: "service", Price: calcPrice(100000) , Brand: "MTL" },
    // { Model: "brickade2", Name: "Brickade 6x6", Class: "service", Price: calcPrice(100000) , Brand: "MTL" },
    // { Model: "bus", Name: "Bus", Class: "service", Price: calcPrice(100000) , Brand: "Brute" },
    // { Model: "cablecar", Name: "Cable Car", Class: "service", Price: calcPrice(100000) , Brand: "Unknown" },
    // { Model: "coach", Name: "Dashound", Class: "service", Price: calcPrice(100000) , Brand: "Brute" },
    // { Model: "rallytruck", Name: "Dune", Class: "service", Price: calcPrice(100000) , Brand: "MTL" },
    // { Model: "pbus2", Name: "Festival Bus", Class: "service", Price: calcPrice(100000) , Brand: "Unknown" },
    // { Model: "freight", Name: "Freight Train", Class: "service", Price: calcPrice(100000) , Brand: "Unknown" },
    // { Model: "metrotrain", Name: "Metro Train", Class: "service", Price: calcPrice(100000) , Brand: "Unknown" },
    // { Model: "rentalbus", Name: "Rental Shuttle Bus", Class: "service", Price: calcPrice(100000) , Brand: "Brute" },
    // { Model: "taxi", Name: "Taxi", Class: "service", Price: calcPrice(100000) , Brand: "Vapid" },
    // { Model: "tourbus", Name: "Tour Bus", Class: "service", Price: calcPrice(100000) , Brand: "Brute" },
    // { Model: "trash", Name: "Trashmaster", Class: "service", Price: calcPrice(100000) , Brand: "JoBuilt" },
    // { Model: "trash2", Name: "Trashmaster", Class: "service", Price: calcPrice(100000) , Brand: "JoBuilt" },
    // { Model: "wastelander", Name: "Wastelander", Class: "service", Price: calcPrice(100000) , Brand: "MTL" },
    // { Model: "fbi", Name: "FIB Buffalo", Class: "emergency", Price: calcPrice(40000) , Brand: "Bravado" },
    // { Model: "fbi2", Name: "FIB Granger", Class: "emergency", Price: calcPrice(40000) , Brand: "Declasse" },
    // { Model: "polgauntlet", Name: "Gauntlet Interceptor", Class: "emergency", Price: calcPrice(40000) , Brand: "Bravado" },
    // { Model: "pranger", Name: "Park Ranger", Class: "emergency", Price: calcPrice(40000) , Brand: "Declasse" },
    // { Model: "predator", Name: "Police Predator", Class: "emergency", Price: calcPrice(40000) , Brand: "Unknown" },
    // { Model: "seashark2", Name: "Seashark Lifeguard", Class: "emergency", Price: calcPrice(40000) , Brand: "Speedophile" },
    // { Model: "police5", Name: "Stanier LE Cruiser", Class: "emergency", Price: calcPrice(40000) , Brand: "Vapid" },
    // { Model: "policet3", Name: "Burrito (Bail Enforcement)", Class: "emergency", Price: calcPrice(60000) , Brand: "Declasse" },
    // { Model: "poldorado", Name: "Dorado Cruiser", Class: "emergency", Price: calcPrice(80000) , Brand: "Vapid" },
    // { Model: "polgreenwood", Name: "Greenwood Cruiser", Class: "emergency", Price: calcPrice(80000) , Brand: "Bravado" },
    // { Model: "polimpaler5", Name: "Impaler SZ Cruiser", Class: "emergency", Price: calcPrice(80000) , Brand: "Declasse" },
    // { Model: "polimpaler6", Name: "Impaler LX Cruiser", Class: "emergency", Price: calcPrice(90000) , Brand: "Declasse" },
    // { Model: "police2", Name: "Police Buffalo", Class: "emergency", Price: calcPrice(100000) , Brand: "Vapid" },
    // { Model: "police", Name: "Police Cruiser", Class: "emergency", Price: calcPrice(100000) , Brand: "Vapid" },
    // { Model: "police3", Name: "Police Interceptor", Class: "emergency", Price: calcPrice(100000) , Brand: "Vapid" },
    // { Model: "pbus", Name: "Police Prison Bus", Class: "emergency", Price: calcPrice(100000) , Brand: "Vapid" },
    // { Model: "riot", Name: "Police Riot", Class: "emergency", Price: calcPrice(100000) , Brand: "Brute" },
    // { Model: "riot2", Name: "RCV", Class: "emergency", Price: calcPrice(100000) , Brand: "Unknown" },
    // { Model: "sheriff2", Name: "Sheriff Cruiser", Class: "emergency", Price: calcPrice(100000) , Brand: "Vapid" },
    // { Model: "sheriff", Name: "Sheriff SUV", Class: "emergency", Price: calcPrice(100000) , Brand: "Declasse" },
    // { Model: "police4", Name: "Unmarked Cruiser", Class: "emergency", Price: calcPrice(100000) , Brand: "Vapid" },
    // { Model: "ambulance", Name: "Ambulance", Class: "emergency", Price: calcPrice(110000) , Brand: "Brute" },
    // { Model: "firetruk", Name: "Fire Truck", Class: "emergency", Price: calcPrice(110000) , Brand: "MTL" },
    // { Model: "lguard", Name: "Lifeguard", Class: "emergency", Price: calcPrice(110000) , Brand: "Declasse" },
    // { Model: "policeb", Name: "Police Bike", Class: "emergency", Price: calcPrice(110000) , Brand: "Vapid" },
    // { Model: "polmav", Name: "Police Maverick", Class: "emergency", Price: calcPrice(110000) , Brand: "Buckingham" },
    // { Model: "policeold1", Name: "Police Rancher", Class: "emergency", Price: calcPrice(110000) , Brand: "Declasse" },
    // { Model: "policeold2", Name: "Police Roadcruiser", Class: "emergency", Price: calcPrice(110000) , Brand: "Albany" },
    // { Model: "policet", Name: "Police Transporter", Class: "emergency", Price: calcPrice(110000) , Brand: "Vapid" },
    // { Model: "poldominator10", Name: "Dominator FX Interceptor", Class: "emergency", Price: calcPrice(230000) , Brand: "Vapid" },
    // { Model: "trailersmall2", Name: "Anti-Aircraft Trailer", Class: "military", Price: calcPrice(100000) , Brand: "Vom Feuer" },
    // { Model: "apc", Name: "APC Tank", Class: "military", Price: calcPrice(100000) , Brand: "HVY" },
    // { Model: "barracks", Name: "Barracks", Class: "military", Price: calcPrice(100000) , Brand: "HVY" },
    // { Model: "barracks3", Name: "Barracks", Class: "military", Price: calcPrice(100000) , Brand: "HVY" },
    // { Model: "barracks2", Name: "Barracks Semi", Class: "military", Price: calcPrice(100000) , Brand: "HVY" },
    // { Model: "barrage", Name: "Barrage", Class: "military", Price: calcPrice(100000) , Brand: "HVY" },
    // { Model: "chernobog", Name: "Chernobog", Class: "military", Price: calcPrice(100000) , Brand: "HVY" },
    // { Model: "crusader", Name: "Crusader", Class: "military", Price: calcPrice(100000) , Brand: "Canis" },
    // { Model: "halftrack", Name: "Half-track", Class: "military", Price: calcPrice(100000) , Brand: "Bravado" },
    // { Model: "kosatka", Name: "Kosatka", Class: "military", Price: calcPrice(100000) , Brand: "Rune" },
    // { Model: "trailerlarge", Name: "Mobile Operations Center", Class: "military", Price: calcPrice(100000) , Brand: "Unknown" },
    // { Model: "minitank", Name: "RC Tank", Class: "military", Price: calcPrice(100000) , Brand: "Unknown" },
    // { Model: "rhino", Name: "Rhino Tank", Class: "military", Price: calcPrice(100000) , Brand: "Unknown" },
    // { Model: "scarab", Name: "Scarab", Class: "military", Price: calcPrice(100000) , Brand: "HVY" },
    // { Model: "terbyte", Name: "Terrorbyte", Class: "military", Price: calcPrice(100000) , Brand: "Benefactor" },
    // { Model: "thruster", Name: "Thruster", Class: "military", Price: calcPrice(100000) , Brand: "Mammoth" },
    // { Model: "khanjali", Name: "TM-02 Khanjali Tank", Class: "military", Price: calcPrice(100000) , Brand: "Unknown" },
    // { Model: "vetir", Name: "Vetir", Class: "military", Price: calcPrice(100000) , Brand: "Unknown" },
    // { Model: "mule", Name: "Mule", Class: "commercial", Price: calcPrice(40000) , Brand: "Maibatsu" },
    // { Model: "mule5", Name: "Mule (Heist)", Class: "commercial", Price: calcPrice(40000) , Brand: "Maibatsu" },
    // { Model: "mule4", Name: "Mule Custom", Class: "commercial", Price: calcPrice(40000) , Brand: "Maibatsu" },
    // { Model: "benson", Name: "Benson", Class: "commercial", Price: calcPrice(55000) , Brand: "Vapid" },
    // { Model: "benson2", Name: "Benson (Cluckin Bell)", Class: "commercial", Price: calcPrice(55000) , Brand: "Vapid" },
    // { Model: "pounder", Name: "Pounder", Class: "commercial", Price: calcPrice(55000) , Brand: "MTL" },
    // { Model: "pounder2", Name: "Pounder Custom", Class: "commercial", Price: calcPrice(55000) , Brand: "MTL" },
    // { Model: "cerberus", Name: "Apocalypse Cerberus", Class: "commercial", Price: calcPrice(100000) , Brand: "MTL" },
    // { Model: "biff", Name: "Biff", Class: "commercial", Price: calcPrice(100000) , Brand: "Brute" },
    // { Model: "hauler", Name: "Hauler", Class: "commercial", Price: calcPrice(100000) , Brand: "Jobuilt" },
    // { Model: "hauler2", Name: "Hauler Custom", Class: "commercial", Price: calcPrice(100000) , Brand: "Jobuilt" },
    // { Model: "packer", Name: "Packer", Class: "commercial", Price: calcPrice(100000) , Brand: "MTL" },
    // { Model: "phantom", Name: "Phantom", Class: "commercial", Price: calcPrice(100000) , Brand: "Jobuilt" },
    // { Model: "phantom4", Name: "Phantom (Christmas)", Class: "commercial", Price: calcPrice(100000) , Brand: "Vapid" },
    // { Model: "phantom2", Name: "Phantom Wedge", Class: "commercial", Price: calcPrice(100000) , Brand: "Jobuilt" },
    // { Model: "stockade", Name: "Stockade", Class: "commercial", Price: calcPrice(100000) , Brand: "Brute" },
    // { Model: "phantom3", Name: "Phantom Custom", Class: "commercial", Price: calcPrice(110000) , Brand: "Jobuilt" },
    // { Model: "openwheel1", Name: "BR8", Class: "openwheel", Price: calcPrice(100000) , Brand: "Benefactor" },
    // { Model: "openwheel2", Name: "DR1", Class: "openwheel", Price: calcPrice(100000) , Brand: "Declasse" },
    // { Model: "formula", Name: "PR4", Class: "openwheel", Price: calcPrice(100000) , Brand: "Progen" },
    // { Model: "formula2", Name: "R88", Class: "openwheel", Price: calcPrice(100000) , Brand: "Ocelot" }
]




console.log(carV3.filter(car=>car.Class === "SEDAN").length)