const RentalMultiplier = 1
export const carRentalsConfig= [
    {
        vehicleModel: 'faggio',
        name: 'Faggio',
        rentalPrice:Math.floor( 250 * RentalMultiplier),
        fuelType: 'REGULAR',
        type: 'motorcycle',
        class: 'MOTORCYCLE',
    },
    {
        vehicleModel: 'faggio2',
        name: 'Faggio Mod',
        rentalPrice:Math.floor( 350 * RentalMultiplier),
        fuelType: 'REGULAR',
        type: 'motorcycle',
        class: 'MOTORCYCLE',
    },
    {
        vehicleModel: 'akuma',
        name: 'Akuma',
        rentalPrice:Math.floor( 1000 * RentalMultiplier),
        fuelType: 'REGULAR',
        type: 'motorcycle',
        class: 'SPORT',
    },
    {
        vehicleModel: 'virgo',
        name: 'Virgo',
        rentalPrice:Math.floor( 1250 * RentalMultiplier),
        fuelType: 'REGULAR',
        type: 'vehicle',
        class: 'MUSCLE',
    },
    {
        vehicleModel: 'glendale',
        name: 'Glendale',
        rentalPrice:Math.floor( 1350 * RentalMultiplier),
        fuelType: 'REGULAR',
        type: 'vehicle',
        class: 'SEDAN',
    },
    {
        vehicleModel: 'washington',
        name: 'Washington',
        rentalPrice:Math.floor( 1400 * RentalMultiplier),
        fuelType: 'REGULAR',
        type: 'vehicle',
        class: 'SEDAN',
    },
    {
        vehicleModel: 'sentinel',
        name: 'Sentinel',
        rentalPrice:Math.floor( 1500 * RentalMultiplier),
        fuelType: 'REGULAR',
        type: 'vehicle',
        class: 'COUPE',
    },
    {
        vehicleModel: 'brioso',
        name: 'Brioso R/A',
        rentalPrice:Math.floor( 1700 * RentalMultiplier),
        fuelType: 'REGULAR',
        type: 'vehicle',
        class: 'COMPACT',
    },
    {
        vehicleModel: 'asbo',
        name: 'Asbo',
        rentalPrice:Math.floor( 1800 * RentalMultiplier),
        fuelType: 'REGULAR',
        type: 'vehicle',
        class: 'COMPACT',
    },

    {
        vehicleModel: 'zion',
        name: 'Zion',
        rentalPrice:Math.floor( 1900 * RentalMultiplier),
        fuelType: 'REGULAR',
        type: 'vehicle',
        class: 'COUPE',
    },

    {
        vehicleModel: 'radi',
        name: 'Radius',
        rentalPrice:Math.floor( 2400 * RentalMultiplier),
        fuelType: 'REGULAR',
        type: 'vehicle',
        class: 'SUV',
    },

    {
        vehicleModel: 'jester2',
        name: 'Jester (Racecar)',
        rentalPrice:Math.floor( 5500 * RentalMultiplier),
        fuelType: 'REGULAR',
        type: 'vehicle',
        class: 'SPORT',
    },
];