const RentalMultiplier = 1
export const carRentalsConfig= [
    {
        vehicleModel: 'faggio',
        name: 'Faggio',
        rentalPrice:( 250 * RentalMultiplier).toFixed(0),
        fuelType: 'REGULAR',
        type: 'motorcycle',
        class: 'MOTORCYCLE',
    },
    {
        vehicleModel: 'faggio2',
        name: 'Faggio Mod',
        rentalPrice:( 350 * RentalMultiplier).toFixed(0),
        fuelType: 'REGULAR',
        type: 'motorcycle',
        class: 'MOTORCYCLE',
    },
    {
        vehicleModel: 'akuma',
        name: 'Akuma',
        rentalPrice:( 1000 * RentalMultiplier).toFixed(0),
        fuelType: 'REGULAR',
        type: 'motorcycle',
        class: 'SPORT',
    },
    {
        vehicleModel: 'virgo',
        name: 'Virgo',
        rentalPrice:( 1250 * RentalMultiplier).toFixed(0),
        fuelType: 'REGULAR',
        type: 'vehicle',
        class: 'MUSCLE',
    },
    {
        vehicleModel: 'glendale',
        name: 'Glendale',
        rentalPrice:( 1350 * RentalMultiplier).toFixed(0),
        fuelType: 'REGULAR',
        type: 'vehicle',
        class: 'SEDAN',
    },
    {
        vehicleModel: 'washington',
        name: 'Washington',
        rentalPrice:( 1400 * RentalMultiplier).toFixed(0),
        fuelType: 'REGULAR',
        type: 'vehicle',
        class: 'SEDAN',
    },
    {
        vehicleModel: 'sentinel',
        name: 'Sentinel',
        rentalPrice:( 1500 * RentalMultiplier).toFixed(0),
        fuelType: 'REGULAR',
        type: 'vehicle',
        class: 'COUPE',
    },
    {
        vehicleModel: 'brioso',
        name: 'Brioso R/A',
        rentalPrice:( 1700 * RentalMultiplier).toFixed(0),
        fuelType: 'REGULAR',
        type: 'vehicle',
        class: 'COMPACT',
    },
    {
        vehicleModel: 'asbo',
        name: 'Asbo',
        rentalPrice:( 1800 * RentalMultiplier).toFixed(0),
        fuelType: 'REGULAR',
        type: 'vehicle',
        class: 'COMPACT',
    },

    {
        vehicleModel: 'zion',
        name: 'Zion',
        rentalPrice:( 1900 * RentalMultiplier).toFixed(0),
        fuelType: 'REGULAR',
        type: 'vehicle',
        class: 'COUPE',
    },

    {
        vehicleModel: 'radi',
        name: 'Radius',
        rentalPrice:( 2400 * RentalMultiplier).toFixed(0),
        fuelType: 'REGULAR',
        type: 'vehicle',
        class: 'SUV',
    },

    {
        vehicleModel: 'jester2',
        name: 'Jester (Racecar)',
        rentalPrice:( 5500 * RentalMultiplier).toFixed(0),
        fuelType: 'REGULAR',
        type: 'vehicle',
        class: 'SPORT',
    },
];